
; AA block{{{
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-0_00* "        ")
(defparameter *aa-0_01* "   _|   ")
(defparameter *aa-0_02* " _|  _| ")
(defparameter *aa-0_03* " _|  _| ")
(defparameter *aa-0_04* " _|  _| ")
(defparameter *aa-0_05* "   _|   ")
(defparameter *aa-0_06* "        ")
(defparameter *aa-0_07* "        ")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-1_00* "        ")
(defparameter *aa-1_01* "   _|   ")
(defparameter *aa-1_02* " _|_|   ")
(defparameter *aa-1_03* "   _|   ")
(defparameter *aa-1_04* "   _|   ")
(defparameter *aa-1_05* "   _|   ")
(defparameter *aa-1_06* "        ")
(defparameter *aa-1_07* "        ")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-2_00* "          ")
(defparameter *aa-2_01* "   _|_|   ")
(defparameter *aa-2_02* " _|    _| ")
(defparameter *aa-2_03* "     _|   ")
(defparameter *aa-2_04* "   _|     ")
(defparameter *aa-2_05* " _|_|_|_| ")
(defparameter *aa-2_06* "          ")
(defparameter *aa-2_07* "          ")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-3_00* "          ")
(defparameter *aa-3_01* " _|_|_|   ")
(defparameter *aa-3_02* "       _| ")
(defparameter *aa-3_03* "   _|_|   ")
(defparameter *aa-3_04* "       _| ")
(defparameter *aa-3_05* " _|_|_|   ")
(defparameter *aa-3_06* "          ")
(defparameter *aa-3_07* "          ")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-4_00* "          ")
(defparameter *aa-4_01* " _|  _|   ")
(defparameter *aa-4_02* " _|  _|   ")
(defparameter *aa-4_03* " _|_|_|_| ")
(defparameter *aa-4_04* "     _|   ")
(defparameter *aa-4_05* "     _|   ")
(defparameter *aa-4_06* "          ")
(defparameter *aa-4_07* "          ")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-5_00* "          ")
(defparameter *aa-5_01* " _|_|_|_| ")
(defparameter *aa-5_02* " _|       ")
(defparameter *aa-5_03* " _|_|_|   ")
(defparameter *aa-5_04* "       _| ")
(defparameter *aa-5_05* " _|_|_|   ")
(defparameter *aa-5_06* "          ")
(defparameter *aa-5_07* "          ")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-6_00* "          ")
(defparameter *aa-6_01* "   _|_|_| ")
(defparameter *aa-6_02* " _|       ")
(defparameter *aa-6_03* " _|_|_|   ")
(defparameter *aa-6_04* " _|    _| ")
(defparameter *aa-6_05* "   _|_|   ")
(defparameter *aa-6_06* "          ")
(defparameter *aa-6_07* "          ")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-7_00* "          ")
(defparameter *aa-7_01* " _|_|_|_| ")
(defparameter *aa-7_02* "      _|  ")
(defparameter *aa-7_03* "    _|    ")
(defparameter *aa-7_04* "   _|     ")
(defparameter *aa-7_05* "  _|      ")
(defparameter *aa-7_06* "          ")
(defparameter *aa-7_07* "          ")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-8_00* "          ")
(defparameter *aa-8_01* "   _|_|   ")
(defparameter *aa-8_02* " _|    _| ")
(defparameter *aa-8_03* "   _|_|   ")
(defparameter *aa-8_04* " _|    _| ")
(defparameter *aa-8_05* "   _|_|   ")
(defparameter *aa-8_06* "          ")
(defparameter *aa-8_07* "          ")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-9_00* "          ")
(defparameter *aa-9_01* "   _|_|   ")
(defparameter *aa-9_02* " _|    _| ")
(defparameter *aa-9_03* "   _|_|_| ")
(defparameter *aa-9_04* "       _| ")
(defparameter *aa-9_05* " _|_|_|   ")
(defparameter *aa-9_06* "          ")
(defparameter *aa-9_07* "          ")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-a_00* "          ")
(defparameter *aa-a_01* "          ")
(defparameter *aa-a_02* "   _|_|_| ")
(defparameter *aa-a_03* " _|    _| ")
(defparameter *aa-a_04* " _|    _| ")
(defparameter *aa-a_05* "   _|_|_| ")
(defparameter *aa-a_06* "          ")
(defparameter *aa-a_07* "          ")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-b_00* "          ")
(defparameter *aa-b_01* " _|       ")
(defparameter *aa-b_02* " _|_|_|   ")
(defparameter *aa-b_03* " _|    _| ")
(defparameter *aa-b_04* " _|    _| ")
(defparameter *aa-b_05* " _|_|_|   ")
(defparameter *aa-b_06* "          ")
(defparameter *aa-b_07* "          ")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-c_00* "          ")
(defparameter *aa-c_01* "          ")
(defparameter *aa-c_02* "   _|_|_| ")
(defparameter *aa-c_03* " _|       ")
(defparameter *aa-c_04* " _|       ")
(defparameter *aa-c_05* "   _|_|_| ")
(defparameter *aa-c_06* "          ")
(defparameter *aa-c_07* "          ")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-d_00* "       _| ")
(defparameter *aa-d_01* "       _| ")
(defparameter *aa-d_02* "   _|_|_| ")
(defparameter *aa-d_03* " _|    _| ")
(defparameter *aa-d_04* " _|    _| ")
(defparameter *aa-d_05* "   _|_|_| ")
(defparameter *aa-d_06* "          ")
(defparameter *aa-d_07* "          ")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-e_00* "          ")
(defparameter *aa-e_01* "          ")
(defparameter *aa-e_02* "   _|_|   ")
(defparameter *aa-e_03* " _|_|_|_| ")
(defparameter *aa-e_04* " _|       ")
(defparameter *aa-e_05* "   _|_|_| ")
(defparameter *aa-e_06* "          ")
(defparameter *aa-e_07* "          ")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-f_00* "          ")
(defparameter *aa-f_01* "     _|_| ")
(defparameter *aa-f_02* "   _|     ")
(defparameter *aa-f_03* " _|_|_|_| ")
(defparameter *aa-f_04* "   _|     ")
(defparameter *aa-f_05* "   _|     ")
(defparameter *aa-f_06* "          ")
(defparameter *aa-f_07* "          ")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-g_00* "          ")
(defparameter *aa-g_01* "          ")
(defparameter *aa-g_02* "   _|_|_| ")
(defparameter *aa-g_03* " _|    _| ")
(defparameter *aa-g_04* " _|    _| ")
(defparameter *aa-g_05* "   _|_|_| ")
(defparameter *aa-g_06* "       _| ")
(defparameter *aa-g_07* "   _|_|   ")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-h_00* "          ")
(defparameter *aa-h_01* " _|       ")
(defparameter *aa-h_02* " _|_|_|   ")
(defparameter *aa-h_03* " _|    _| ")
(defparameter *aa-h_04* " _|    _| ")
(defparameter *aa-h_05* " _|    _| ")
(defparameter *aa-h_06* "          ")
(defparameter *aa-h_07* "          ")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-i_00* "     ")
(defparameter *aa-i_01* "  _| ")
(defparameter *aa-i_02* "     ")
(defparameter *aa-i_03* "  _| ")
(defparameter *aa-i_04* "  _| ")
(defparameter *aa-i_05* "  _| ")
(defparameter *aa-i_06* "     ")
(defparameter *aa-i_07* "     ")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-j_00* "      ")
(defparameter *aa-j_01* "   _| ")
(defparameter *aa-j_02* "      ")
(defparameter *aa-j_03* "   _| ")
(defparameter *aa-j_04* "   _| ")
(defparameter *aa-j_05* "   _| ")
(defparameter *aa-j_06* "  _|  ")
(defparameter *aa-j_07* " _|   ")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-k_00* "          ")
(defparameter *aa-k_01* " _|       ")
(defparameter *aa-k_02* " _|  _|   ")
(defparameter *aa-k_03* " _|_|     ")
(defparameter *aa-k_04* " _|  _|   ")
(defparameter *aa-k_05* " _|    _| ")
(defparameter *aa-k_06* "          ")
(defparameter *aa-k_07* "          ")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-l_00* "     ")
(defparameter *aa-l_01* "  _| ")
(defparameter *aa-l_02* "  _| ")
(defparameter *aa-l_03* "  _| ")
(defparameter *aa-l_04* "  _| ")
(defparameter *aa-l_05* "  _| ")
(defparameter *aa-l_06* "     ")
(defparameter *aa-l_07* "     ")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-m_00* "              ")
(defparameter *aa-m_01* "              ")
(defparameter *aa-m_02* " _|_|_| _|_|  ")
(defparameter *aa-m_03* " _|   _|   _| ")
(defparameter *aa-m_04* " _|   _|   _| ")
(defparameter *aa-m_05* " _|   _|   _| ")
(defparameter *aa-m_06* "              ")
(defparameter *aa-m_07* "              ")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-n_00* "          ")
(defparameter *aa-n_01* "          ")
(defparameter *aa-n_02* "  _|_|_|  ")
(defparameter *aa-n_03* " _|    _| ")
(defparameter *aa-n_04* " _|    _| ")
(defparameter *aa-n_05* " _|    _| ")
(defparameter *aa-n_06* "          ")
(defparameter *aa-n_07* "          ")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-o_00* "          ")
(defparameter *aa-o_01* "          ")
(defparameter *aa-o_02* "   _|_|   ")
(defparameter *aa-o_03* " _|    _| ")
(defparameter *aa-o_04* " _|    _| ")
(defparameter *aa-o_05* "   _|_|   ")
(defparameter *aa-o_06* "          ")
(defparameter *aa-o_07* "          ")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-p_00* "          ")
(defparameter *aa-p_01* "          ")
(defparameter *aa-p_02* " _|_|_|   ")
(defparameter *aa-p_03* " _|    _| ")
(defparameter *aa-p_04* " _|    _| ")
(defparameter *aa-p_05* " _|_|_|   ")
(defparameter *aa-p_06* " _|       ")
(defparameter *aa-p_07* " _|       ")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-q_00* "          ")
(defparameter *aa-q_01* "          ")
(defparameter *aa-q_02* "   _|_|_| ")
(defparameter *aa-q_03* " _|    _| ")
(defparameter *aa-q_04* " _|    _| ")
(defparameter *aa-q_05* "   _|_|_| ")
(defparameter *aa-q_06* "       _| ")
(defparameter *aa-q_07* "       _| ")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-r_00* "          ")
(defparameter *aa-r_01* "          ")
(defparameter *aa-r_02* " _|  _|_| ")
(defparameter *aa-r_03* " _|_|     ")
(defparameter *aa-r_04* " _|       ")
(defparameter *aa-r_05* " _|       ")
(defparameter *aa-r_06* "          ")
(defparameter *aa-r_07* "          ")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-s_00* "          ")
(defparameter *aa-s_01* "          ")
(defparameter *aa-s_02* "   _|_|_| ")
(defparameter *aa-s_03* " _|_|     ")
(defparameter *aa-s_04* "     _|_| ")
(defparameter *aa-s_05* " _|_|_|   ")
(defparameter *aa-s_06* "          ")
(defparameter *aa-s_07* "          ")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-t_00* "          ")
(defparameter *aa-t_01* "   _|     ")
(defparameter *aa-t_02* " _|_|_|_| ")
(defparameter *aa-t_03* "   _|     ")
(defparameter *aa-t_04* "   _|     ")
(defparameter *aa-t_05* "     _|_| ")
(defparameter *aa-t_06* "          ")
(defparameter *aa-t_07* "          ")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-u_00* "          ")
(defparameter *aa-u_01* "          ")
(defparameter *aa-u_02* " _|    _| ")
(defparameter *aa-u_03* " _|    _| ")
(defparameter *aa-u_04* " _|    _| ")
(defparameter *aa-u_05* "   _|_|_| ")
(defparameter *aa-u_06* "          ")
(defparameter *aa-u_07* "          ")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-v_00* "               ")
(defparameter *aa-v_01* "               ")
(defparameter *aa-v_02* "  _|        _| ")
(defparameter *aa-v_03* "   _|      _|  ")
(defparameter *aa-v_04* "     _|  _|    ")
(defparameter *aa-v_05* "       _|      ")
(defparameter *aa-v_06* "               ")
(defparameter *aa-v_07* "               ")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-w_00* "                    ")
(defparameter *aa-w_01* "                    ")
(defparameter *aa-w_02* " _|      _|      _| ")
(defparameter *aa-w_03* "  _|     _|     _|  ")
(defparameter *aa-w_04* "   _|  _|  _|  _|   ")
(defparameter *aa-w_05* "     _|      _|     ")
(defparameter *aa-w_06* "                    ")
(defparameter *aa-w_07* "                    ")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-x_00* "           ")
(defparameter *aa-x_01* "           ")
(defparameter *aa-x_02* "  _|    _| ")
(defparameter *aa-x_03* "    _|_|   ")
(defparameter *aa-x_04* "    _|_|   ")
(defparameter *aa-x_05* "  _|    _| ")
(defparameter *aa-x_06* "           ")
(defparameter *aa-x_07* "           ")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-y_00* "          ")
(defparameter *aa-y_01* "          ")
(defparameter *aa-y_02* " _|    _| ")
(defparameter *aa-y_03* " _|    _| ")
(defparameter *aa-y_04* " _|    _| ")
(defparameter *aa-y_05* "   _|_|_| ")
(defparameter *aa-y_06* "       _| ")
(defparameter *aa-y_07* "   _|_|   ")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-z_00* "           ")
(defparameter *aa-z_01* "           ")
(defparameter *aa-z_02* "  _|_|_|_| ")
(defparameter *aa-z_03* "      _|   ")
(defparameter *aa-z_04* "    _|     ")
(defparameter *aa-z_05* "  _|_|_|_| ")
(defparameter *aa-z_06* "           ")
(defparameter *aa-z_07* "           ")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-La_00* "          ")
(defparameter *aa-La_01* "   _|_|   ")
(defparameter *aa-La_02* " _|    _| ")
(defparameter *aa-La_03* " _|_|_|_| ")
(defparameter *aa-La_04* " _|    _| ")
(defparameter *aa-La_05* " _|    _| ")
(defparameter *aa-La_06* "          ")
(defparameter *aa-La_07* "          ")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-Lb_00* "          ")
(defparameter *aa-Lb_01* " _|_|_|   ")
(defparameter *aa-Lb_02* " _|    _| ")
(defparameter *aa-Lb_03* " _|_|_|   ")
(defparameter *aa-Lb_04* " _|    _| ")
(defparameter *aa-Lb_05* " _|_|_|   ")
(defparameter *aa-Lb_06* "          ")
(defparameter *aa-Lb_07* "          ")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-Lc_00* "          ")
(defparameter *aa-Lc_01* "   _|_|_| ")
(defparameter *aa-Lc_02* " _|       ")
(defparameter *aa-Lc_03* " _|       ")
(defparameter *aa-Lc_04* " _|       ")
(defparameter *aa-Lc_05* "   _|_|_| ")
(defparameter *aa-Lc_06* "          ")
(defparameter *aa-Lc_07* "          ")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-Ld_00* "          ")
(defparameter *aa-Ld_01* " _|_|_|   ")
(defparameter *aa-Ld_02* " _|    _| ")
(defparameter *aa-Ld_03* " _|    _| ")
(defparameter *aa-Ld_04* " _|    _| ")
(defparameter *aa-Ld_05* " _|_|_|   ")
(defparameter *aa-Ld_06* "          ")
(defparameter *aa-Ld_07* "          ")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-Le_00* "          ")
(defparameter *aa-Le_01* " _|_|_|_| ")
(defparameter *aa-Le_02* " _|       ")
(defparameter *aa-Le_03* " _|_|_|   ")
(defparameter *aa-Le_04* " _|       ")
(defparameter *aa-Le_05* " _|_|_|_| ")
(defparameter *aa-Le_06* "          ")
(defparameter *aa-Le_07* "          ")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-Lf_00* "          ")
(defparameter *aa-Lf_01* " _|_|_|_| ")
(defparameter *aa-Lf_02* " _|       ")
(defparameter *aa-Lf_03* " _|_|_|   ")
(defparameter *aa-Lf_04* " _|       ")
(defparameter *aa-Lf_05* " _|       ")
(defparameter *aa-Lf_06* "          ")
(defparameter *aa-Lf_07* "          ")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-Lg_00* "          ")
(defparameter *aa-Lg_01* "   _|_|_| ")
(defparameter *aa-Lg_02* " _|       ")
(defparameter *aa-Lg_03* " _|  _|_| ")
(defparameter *aa-Lg_04* " _|    _| ")
(defparameter *aa-Lg_05* "   _|_|_| ")
(defparameter *aa-Lg_06* "          ")
(defparameter *aa-Lg_07* "          ")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-Lh_00* "          ")
(defparameter *aa-Lh_01* " _|    _| ")
(defparameter *aa-Lh_02* " _|    _| ")
(defparameter *aa-Lh_03* " _|_|_|_| ")
(defparameter *aa-Lh_04* " _|    _| ")
(defparameter *aa-Lh_05* " _|    _| ")
(defparameter *aa-Lh_06* "          ")
(defparameter *aa-Lh_07* "          ")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-Li_00* "        ")
(defparameter *aa-Li_01* " _|_|_| ")
(defparameter *aa-Li_02* "   _|   ")
(defparameter *aa-Li_03* "   _|   ")
(defparameter *aa-Li_04* "   _|   ")
(defparameter *aa-Li_05* " _|_|_| ")
(defparameter *aa-Li_06* "        ")
(defparameter *aa-Li_07* "        ")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-Lj_00* "          ")
(defparameter *aa-Lj_01* "       _| ")
(defparameter *aa-Lj_02* "       _| ")
(defparameter *aa-Lj_03* "       _| ")
(defparameter *aa-Lj_04* " _|    _| ")
(defparameter *aa-Lj_05* "   _|_|   ")
(defparameter *aa-Lj_06* "          ")
(defparameter *aa-Lj_07* "          ")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-Lk_00* "          ")
(defparameter *aa-Lk_01* " _|    _| ")
(defparameter *aa-Lk_02* " _|  _|   ")
(defparameter *aa-Lk_03* " _|_|     ")
(defparameter *aa-Lk_04* " _|  _|   ")
(defparameter *aa-Lk_05* " _|    _| ")
(defparameter *aa-Lk_06* "          ")
(defparameter *aa-Lk_07* "          ")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-Ll_00* "          ")
(defparameter *aa-Ll_01* " _|       ")
(defparameter *aa-Ll_02* " _|       ")
(defparameter *aa-Ll_03* " _|       ")
(defparameter *aa-Ll_04* " _|       ")
(defparameter *aa-Ll_05* " _|_|_|_| ")
(defparameter *aa-Ll_06* "          ")
(defparameter *aa-Ll_07* "          ")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-Lm_00* "           ")
(defparameter *aa-Lm_01* "_|      _| ")
(defparameter *aa-Lm_02* "_|_|  _|_| ")
(defparameter *aa-Lm_03* "_|  _|  _| ")
(defparameter *aa-Lm_04* "_|      _| ")
(defparameter *aa-Lm_05* "_|      _| ")
(defparameter *aa-Lm_06* "           ")
(defparameter *aa-Lm_07* "           ")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-Ln_00* "             ")
(defparameter *aa-Ln_01* "  _|      _| ")
(defparameter *aa-Ln_02* "  _|_|    _| ")
(defparameter *aa-Ln_03* "  _|  _|  _| ")
(defparameter *aa-Ln_04* "  _|    _|_| ")
(defparameter *aa-Ln_05* "  _|      _| ")
(defparameter *aa-Ln_06* "             ")
(defparameter *aa-Ln_07* "             ")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-Lo_00* "          ")
(defparameter *aa-Lo_01* "   _|_|   ")
(defparameter *aa-Lo_02* " _|    _| ")
(defparameter *aa-Lo_03* " _|    _| ")
(defparameter *aa-Lo_04* " _|    _| ")
(defparameter *aa-Lo_05* "   _|_|   ")
(defparameter *aa-Lo_06* "          ")
(defparameter *aa-Lo_07* "          ")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-Lp_00* "          ")
(defparameter *aa-Lp_01* " _|_|_|   ")
(defparameter *aa-Lp_02* " _|    _| ")
(defparameter *aa-Lp_03* " _|_|_|   ")
(defparameter *aa-Lp_04* " _|       ")
(defparameter *aa-Lp_05* " _|       ")
(defparameter *aa-Lp_06* "          ")
(defparameter *aa-Lp_07* "          ")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-Lq_00* "            ")
(defparameter *aa-Lq_01* "   _|_|     ")
(defparameter *aa-Lq_02* " _|    _|   ")
(defparameter *aa-Lq_03* " _|  _|_|   ")
(defparameter *aa-Lq_04* " _|    _|   ")
(defparameter *aa-Lq_05* "   _|_|  _| ")
(defparameter *aa-Lq_06* "            ")
(defparameter *aa-Lq_07* "            ")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-Lr_00* "          ")
(defparameter *aa-Lr_01* " _|_|_|   ")
(defparameter *aa-Lr_02* " _|    _| ")
(defparameter *aa-Lr_03* " _|_|_|   ")
(defparameter *aa-Lr_04* " _|    _| ")
(defparameter *aa-Lr_05* " _|    _| ")
(defparameter *aa-Lr_06* "          ")
(defparameter *aa-Lr_07* "          ")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-Ls_00* "          ")
(defparameter *aa-Ls_01* "   _|_|_| ")
(defparameter *aa-Ls_02* " _|       ")
(defparameter *aa-Ls_03* "   _|_|   ")
(defparameter *aa-Ls_04* "       _| ")
(defparameter *aa-Ls_05* " _|_|_|   ")
(defparameter *aa-Ls_06* "          ")
(defparameter *aa-Ls_07* "          ")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-Lt_00* "            ")
(defparameter *aa-Lt_01* " _|_|_|_|_| ")
(defparameter *aa-Lt_02* "     _|     ")
(defparameter *aa-Lt_03* "     _|     ")
(defparameter *aa-Lt_04* "     _|     ")
(defparameter *aa-Lt_05* "     _|     ")
(defparameter *aa-Lt_06* "            ")
(defparameter *aa-Lt_07* "            ")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-Lu_00* "          ")
(defparameter *aa-Lu_01* " _|    _| ")
(defparameter *aa-Lu_02* " _|    _| ")
(defparameter *aa-Lu_03* " _|    _| ")
(defparameter *aa-Lu_04* " _|    _| ")
(defparameter *aa-Lu_05* "   _|_|   ")
(defparameter *aa-Lu_06* "          ")
(defparameter *aa-Lu_07* "          ")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-Lv_00* "               ")
(defparameter *aa-Lv_01* " _|         _| ")
(defparameter *aa-Lv_02* "  _|       _|  ")
(defparameter *aa-Lv_03* "   _|     _|   ")
(defparameter *aa-Lv_04* "     _|  _|    ")
(defparameter *aa-Lv_05* "       _|      ")
(defparameter *aa-Lv_06* "               ")
(defparameter *aa-Lv_07* "               ")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-Lw_00* "                ")
(defparameter *aa-Lw_01* " _|          _| ")
(defparameter *aa-Lw_02* " _|          _| ")
(defparameter *aa-Lw_03* " _|    _|    _| ")
(defparameter *aa-Lw_04* "   _|  _|  _|   ")
(defparameter *aa-Lw_05* "     _|  _|     ")
(defparameter *aa-Lw_06* "                ")
(defparameter *aa-Lw_07* "                ")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-Lx_00* "            ")
(defparameter *aa-Lx_01* " _|      _| ")
(defparameter *aa-Lx_02* "   _|  _|   ")
(defparameter *aa-Lx_03* "     _|     ")
(defparameter *aa-Lx_04* "   _|  _|   ")
(defparameter *aa-Lx_05* " _|      _| ")
(defparameter *aa-Lx_06* "            ")
(defparameter *aa-Lx_07* "            ")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-Ly_00* "            ")
(defparameter *aa-Ly_01* " _|      _| ")
(defparameter *aa-Ly_02* "   _|  _|   ")
(defparameter *aa-Ly_03* "     _|     ")
(defparameter *aa-Ly_04* "     _|     ")
(defparameter *aa-Ly_05* "     _|     ")
(defparameter *aa-Ly_06* "            ")
(defparameter *aa-Ly_07* "            ")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-Lz_00* "            ")
(defparameter *aa-Lz_01* " _|_|_|_|_| ")
(defparameter *aa-Lz_02* "       _|   ")
(defparameter *aa-Lz_03* "     _|     ")
(defparameter *aa-Lz_04* "   _|       ")
(defparameter *aa-Lz_05* " _|_|_|_|_| ")
(defparameter *aa-Lz_06* "            ")
(defparameter *aa-Lz_07* "            ")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-dot_00* "    ")
(defparameter *aa-dot_01* "    ")
(defparameter *aa-dot_02* "    ")
(defparameter *aa-dot_03* "    ")
(defparameter *aa-dot_04* "    ")
(defparameter *aa-dot_05* " _| ")
(defparameter *aa-dot_06* "    ")
(defparameter *aa-dot_07* "    ")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-Question_00* "        ")
(defparameter *aa-Question_01* " _|_|   ")
(defparameter *aa-Question_02* "     _| ")
(defparameter *aa-Question_03* " _|_|   ")
(defparameter *aa-Question_04* "        ")
(defparameter *aa-Question_05* " _|     ")
(defparameter *aa-Question_06* "        ")
(defparameter *aa-Question_07* "        ")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-exc_00* "    ")
(defparameter *aa-exc_01* " _| ")
(defparameter *aa-exc_02* " _| ")
(defparameter *aa-exc_03* " _| ")
(defparameter *aa-exc_04* "    ")
(defparameter *aa-exc_05* " _| ")
(defparameter *aa-exc_06* "    ")
(defparameter *aa-exc_07* "    ")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-hyphen_00* "            ")
(defparameter *aa-hyphen_01* "            ")
(defparameter *aa-hyphen_02* "            ")
(defparameter *aa-hyphen_03* " _|_|_|_|_| ")
(defparameter *aa-hyphen_04* "            ")
(defparameter *aa-hyphen_05* "            ")
(defparameter *aa-hyphen_06* "            ")
(defparameter *aa-hyphen_07* "            ")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-Space_00* "    ")
(defparameter *aa-Space_01* "    ")
(defparameter *aa-Space_02* "    ")
(defparameter *aa-Space_03* "    ")
(defparameter *aa-Space_04* "    ")
(defparameter *aa-Space_05* "    ")
(defparameter *aa-Space_06* "    ")
(defparameter *aa-Space_07* "    ")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;}}}
; AA Slash block{{{
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-sla-0_00* "********")
(defparameter *aa-sla-0_01* "////////")
(defparameter *aa-sla-0_02* "///_|///")
(defparameter *aa-sla-0_03* "/_|//_|/")
(defparameter *aa-sla-0_04* "/_|//_|/")
(defparameter *aa-sla-0_05* "/_|//_|/")
(defparameter *aa-sla-0_06* "///_|///")
(defparameter *aa-sla-0_07* "////////")
(defparameter *aa-sla-0_08* "////////")
(defparameter *aa-sla-0_09* "********")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-sla-1_00* "********")
(defparameter *aa-sla-1_01* "////////")
(defparameter *aa-sla-1_02* "///_|///")
(defparameter *aa-sla-1_03* "/_|_|///")
(defparameter *aa-sla-1_04* "///_|///")
(defparameter *aa-sla-1_05* "///_|///")
(defparameter *aa-sla-1_06* "///_|///")
(defparameter *aa-sla-1_07* "////////")
(defparameter *aa-sla-1_08* "////////")
(defparameter *aa-sla-1_09* "********")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-sla-2_00* "**********")
(defparameter *aa-sla-2_01* "//////////")
(defparameter *aa-sla-2_02* "///_|_|///")
(defparameter *aa-sla-2_03* "/_|////_|/")
(defparameter *aa-sla-2_04* "/////_|///")
(defparameter *aa-sla-2_05* "///_|/////")
(defparameter *aa-sla-2_06* "/_|_|_|_|/")
(defparameter *aa-sla-2_07* "//////////")
(defparameter *aa-sla-2_08* "//////////")
(defparameter *aa-sla-2_09* "**********")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-sla-3_00* "**********")
(defparameter *aa-sla-3_01* "//////////")
(defparameter *aa-sla-3_02* "/_|_|_|///")
(defparameter *aa-sla-3_03* "///////_|/")
(defparameter *aa-sla-3_04* "///_|_|///")
(defparameter *aa-sla-3_05* "///////_|/")
(defparameter *aa-sla-3_06* "/_|_|_|///")
(defparameter *aa-sla-3_07* "//////////")
(defparameter *aa-sla-3_08* "//////////")
(defparameter *aa-sla-3_09* "**********")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-sla-4_00* "**********")
(defparameter *aa-sla-4_01* "//////////")
(defparameter *aa-sla-4_02* "/_|//_|///")
(defparameter *aa-sla-4_03* "/_|//_|///")
(defparameter *aa-sla-4_04* "/_|_|_|_|/")
(defparameter *aa-sla-4_05* "/////_|///")
(defparameter *aa-sla-4_06* "/////_|///")
(defparameter *aa-sla-4_07* "//////////")
(defparameter *aa-sla-4_08* "//////////")
(defparameter *aa-sla-4_09* "**********")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-sla-5_00* "**********")
(defparameter *aa-sla-5_01* "//////////")
(defparameter *aa-sla-5_02* "/_|_|_|_|/")
(defparameter *aa-sla-5_03* "/_|///////")
(defparameter *aa-sla-5_04* "/_|_|_|///")
(defparameter *aa-sla-5_05* "///////_|/")
(defparameter *aa-sla-5_06* "/_|_|_|///")
(defparameter *aa-sla-5_07* "//////////")
(defparameter *aa-sla-5_08* "//////////")
(defparameter *aa-sla-5_09* "**********")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-sla-6_00* "**********")
(defparameter *aa-sla-6_01* "//////////")
(defparameter *aa-sla-6_02* "///_|_|_|/")
(defparameter *aa-sla-6_03* "/_|///////")
(defparameter *aa-sla-6_04* "/_|_|_|///")
(defparameter *aa-sla-6_05* "/_|////_|/")
(defparameter *aa-sla-6_06* "///_|_|///")
(defparameter *aa-sla-6_07* "//////////")
(defparameter *aa-sla-6_08* "//////////")
(defparameter *aa-sla-6_09* "**********")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-sla-7_00* "**********")
(defparameter *aa-sla-7_01* "//////////")
(defparameter *aa-sla-7_02* "/_|_|_|_|/")
(defparameter *aa-sla-7_03* "//////_|//")
(defparameter *aa-sla-7_04* "////_|////")
(defparameter *aa-sla-7_05* "///_|/////")
(defparameter *aa-sla-7_06* "//_|//////")
(defparameter *aa-sla-7_07* "//////////")
(defparameter *aa-sla-7_08* "//////////")
(defparameter *aa-sla-7_09* "**********")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-sla-8_00* "**********")
(defparameter *aa-sla-8_01* "//////////")
(defparameter *aa-sla-8_02* "///_|_|///")
(defparameter *aa-sla-8_03* "/_|////_|/")
(defparameter *aa-sla-8_04* "///_|_|///")
(defparameter *aa-sla-8_05* "/_|////_|/")
(defparameter *aa-sla-8_06* "///_|_|///")
(defparameter *aa-sla-8_07* "//////////")
(defparameter *aa-sla-8_08* "//////////")
(defparameter *aa-sla-8_09* "**********")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-sla-9_00* "**********")
(defparameter *aa-sla-9_01* "//////////")
(defparameter *aa-sla-9_02* "///_|_|///")
(defparameter *aa-sla-9_03* "/_|////_|/")
(defparameter *aa-sla-9_04* "///_|_|_|/")
(defparameter *aa-sla-9_05* "///////_|/")
(defparameter *aa-sla-9_06* "/_|_|_|///")
(defparameter *aa-sla-9_07* "//////////")
(defparameter *aa-sla-9_08* "//////////")
(defparameter *aa-sla-9_09* "**********")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-sla-a_00* "**********")
(defparameter *aa-sla-a_01* "//////////")
(defparameter *aa-sla-a_02* "//////////")
(defparameter *aa-sla-a_03* "///_|_|_|/")
(defparameter *aa-sla-a_04* "/_|////_|/")
(defparameter *aa-sla-a_05* "/_|////_|/")
(defparameter *aa-sla-a_06* "///_|_|_|/")
(defparameter *aa-sla-a_07* "//////////")
(defparameter *aa-sla-a_08* "//////////")
(defparameter *aa-sla-a_09* "**********")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-sla-b_00* "**********")
(defparameter *aa-sla-b_01* "//////////")
(defparameter *aa-sla-b_02* "/_|///////")
(defparameter *aa-sla-b_03* "/_|_|_|///")
(defparameter *aa-sla-b_04* "/_|////_|/")
(defparameter *aa-sla-b_05* "/_|////_|/")
(defparameter *aa-sla-b_06* "/_|_|_|///")
(defparameter *aa-sla-b_07* "//////////")
(defparameter *aa-sla-b_08* "//////////")
(defparameter *aa-sla-b_09* "**********")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-sla-c_00* "**********")
(defparameter *aa-sla-c_01* "//////////")
(defparameter *aa-sla-c_02* "//////////")
(defparameter *aa-sla-c_03* "///_|_|_|/")
(defparameter *aa-sla-c_04* "/_|///////")
(defparameter *aa-sla-c_05* "/_|///////")
(defparameter *aa-sla-c_06* "///_|_|_|/")
(defparameter *aa-sla-c_07* "//////////")
(defparameter *aa-sla-c_08* "//////////")
(defparameter *aa-sla-c_09* "**********")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-sla-d_00* "**********")
(defparameter *aa-sla-d_01* "///////_|/")
(defparameter *aa-sla-d_02* "///////_|/")
(defparameter *aa-sla-d_03* "///_|_|_|/")
(defparameter *aa-sla-d_04* "/_|////_|/")
(defparameter *aa-sla-d_05* "/_|////_|/")
(defparameter *aa-sla-d_06* "///_|_|_|/")
(defparameter *aa-sla-d_07* "//////////")
(defparameter *aa-sla-d_08* "//////////")
(defparameter *aa-sla-d_09* "**********")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-sla-e_00* "**********")
(defparameter *aa-sla-e_01* "//////////")
(defparameter *aa-sla-e_02* "//////////")
(defparameter *aa-sla-e_03* "///_|_|///")
(defparameter *aa-sla-e_04* "/_|_|_|_|/")
(defparameter *aa-sla-e_05* "/_|///////")
(defparameter *aa-sla-e_06* "///_|_|_|/")
(defparameter *aa-sla-e_07* "//////////")
(defparameter *aa-sla-e_08* "//////////")
(defparameter *aa-sla-e_09* "**********")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-sla-f_00* "**********")
(defparameter *aa-sla-f_01* "//////////")
(defparameter *aa-sla-f_02* "/////_|_|/")
(defparameter *aa-sla-f_03* "///_|/////")
(defparameter *aa-sla-f_04* "/_|_|_|_|/")
(defparameter *aa-sla-f_05* "///_|/////")
(defparameter *aa-sla-f_06* "///_|/////")
(defparameter *aa-sla-f_07* "//////////")
(defparameter *aa-sla-f_08* "//////////")
(defparameter *aa-sla-f_09* "**********")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-sla-g_00* "**********")
(defparameter *aa-sla-g_01* "//////////")
(defparameter *aa-sla-g_02* "//////////")
(defparameter *aa-sla-g_03* "///_|_|_|/")
(defparameter *aa-sla-g_04* "/_|////_|/")
(defparameter *aa-sla-g_05* "/_|////_|/")
(defparameter *aa-sla-g_06* "///_|_|_|/")
(defparameter *aa-sla-g_07* "///////_|/")
(defparameter *aa-sla-g_08* "///_|_|///")
(defparameter *aa-sla-g_09* "**********")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-sla-h_00* "**********")
(defparameter *aa-sla-h_01* "//////////")
(defparameter *aa-sla-h_02* "/_|///////")
(defparameter *aa-sla-h_03* "/_|_|_|///")
(defparameter *aa-sla-h_04* "/_|////_|/")
(defparameter *aa-sla-h_05* "/_|////_|/")
(defparameter *aa-sla-h_06* "/_|////_|/")
(defparameter *aa-sla-h_07* "//////////")
(defparameter *aa-sla-h_08* "//////////")
(defparameter *aa-sla-h_09* "**********")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-sla-i_00* "*****")
(defparameter *aa-sla-i_01* "/////")
(defparameter *aa-sla-i_02* "//_|/")
(defparameter *aa-sla-i_03* "/////")
(defparameter *aa-sla-i_04* "//_|/")
(defparameter *aa-sla-i_05* "//_|/")
(defparameter *aa-sla-i_06* "//_|/")
(defparameter *aa-sla-i_07* "/////")
(defparameter *aa-sla-i_08* "/////")
(defparameter *aa-sla-i_09* "*****")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-sla-j_00* "******")
(defparameter *aa-sla-j_01* "//////")
(defparameter *aa-sla-j_02* "///_|/")
(defparameter *aa-sla-j_03* "//////")
(defparameter *aa-sla-j_04* "///_|/")
(defparameter *aa-sla-j_05* "///_|/")
(defparameter *aa-sla-j_06* "///_|/")
(defparameter *aa-sla-j_07* "//_|//")
(defparameter *aa-sla-j_08* "/_|///")
(defparameter *aa-sla-j_09* "******")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-sla-k_00* "**********")
(defparameter *aa-sla-k_01* "//////////")
(defparameter *aa-sla-k_02* "/_|///////")
(defparameter *aa-sla-k_03* "/_|//_|///")
(defparameter *aa-sla-k_04* "/_|_|/////")
(defparameter *aa-sla-k_05* "/_|//_|///")
(defparameter *aa-sla-k_06* "/_|////_|/")
(defparameter *aa-sla-k_07* "//////////")
(defparameter *aa-sla-k_08* "//////////")
(defparameter *aa-sla-k_09* "**********")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-sla-l_00* "*****")
(defparameter *aa-sla-l_01* "/////")
(defparameter *aa-sla-l_02* "//_|/")
(defparameter *aa-sla-l_03* "//_|/")
(defparameter *aa-sla-l_04* "//_|/")
(defparameter *aa-sla-l_05* "//_|/")
(defparameter *aa-sla-l_06* "//_|/")
(defparameter *aa-sla-l_07* "/////")
(defparameter *aa-sla-l_08* "/////")
(defparameter *aa-sla-l_09* "*****")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-sla-m_00* "**************")
(defparameter *aa-sla-m_01* "//////////////")
(defparameter *aa-sla-m_02* "//////////////")
(defparameter *aa-sla-m_03* "/_|_|_|/_|_|//")
(defparameter *aa-sla-m_04* "/_|///_|///_|/")
(defparameter *aa-sla-m_05* "/_|///_|///_|/")
(defparameter *aa-sla-m_06* "/_|///_|///_|/")
(defparameter *aa-sla-m_07* "//////////////")
(defparameter *aa-sla-m_08* "//////////////")
(defparameter *aa-sla-m_09* "**************")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-sla-n_00* "**********")
(defparameter *aa-sla-n_01* "//////////")
(defparameter *aa-sla-n_02* "//////////")
(defparameter *aa-sla-n_03* "//_|_|_|//")
(defparameter *aa-sla-n_04* "/_|////_|/")
(defparameter *aa-sla-n_05* "/_|////_|/")
(defparameter *aa-sla-n_06* "/_|////_|/")
(defparameter *aa-sla-n_07* "//////////")
(defparameter *aa-sla-n_08* "//////////")
(defparameter *aa-sla-n_09* "**********")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-sla-o_00* "**********")
(defparameter *aa-sla-o_01* "//////////")
(defparameter *aa-sla-o_02* "//////////")
(defparameter *aa-sla-o_03* "///_|_|///")
(defparameter *aa-sla-o_04* "/_|////_|/")
(defparameter *aa-sla-o_05* "/_|////_|/")
(defparameter *aa-sla-o_06* "///_|_|///")
(defparameter *aa-sla-o_07* "//////////")
(defparameter *aa-sla-o_08* "//////////")
(defparameter *aa-sla-o_09* "**********")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-sla-p_00* "**********")
(defparameter *aa-sla-p_01* "//////////")
(defparameter *aa-sla-p_02* "//////////")
(defparameter *aa-sla-p_03* "/_|_|_|///")
(defparameter *aa-sla-p_04* "/_|////_|/")
(defparameter *aa-sla-p_05* "/_|////_|/")
(defparameter *aa-sla-p_06* "/_|_|_|///")
(defparameter *aa-sla-p_07* "/_|///////")
(defparameter *aa-sla-p_08* "/_|///////")
(defparameter *aa-sla-p_09* "**********")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-sla-q_00* "**********")
(defparameter *aa-sla-q_01* "//////////")
(defparameter *aa-sla-q_02* "//////////")
(defparameter *aa-sla-q_03* "///_|_|_|/")
(defparameter *aa-sla-q_04* "/_|////_|/")
(defparameter *aa-sla-q_05* "/_|////_|/")
(defparameter *aa-sla-q_06* "///_|_|_|/")
(defparameter *aa-sla-q_07* "///////_|/")
(defparameter *aa-sla-q_08* "///////_|/")
(defparameter *aa-sla-q_09* "**********")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-sla-r_00* "**********")
(defparameter *aa-sla-r_01* "//////////")
(defparameter *aa-sla-r_02* "//////////")
(defparameter *aa-sla-r_03* "/_|//_|_|/")
(defparameter *aa-sla-r_04* "/_|_|/////")
(defparameter *aa-sla-r_05* "/_|///////")
(defparameter *aa-sla-r_06* "/_|///////")
(defparameter *aa-sla-r_07* "//////////")
(defparameter *aa-sla-r_08* "//////////")
(defparameter *aa-sla-r_09* "**********")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-sla-s_00* "**********")
(defparameter *aa-sla-s_01* "//////////")
(defparameter *aa-sla-s_02* "//////////")
(defparameter *aa-sla-s_03* "///_|_|_|/")
(defparameter *aa-sla-s_04* "/_|_|/////")
(defparameter *aa-sla-s_05* "/////_|_|/")
(defparameter *aa-sla-s_06* "/_|_|_|///")
(defparameter *aa-sla-s_07* "//////////")
(defparameter *aa-sla-s_08* "//////////")
(defparameter *aa-sla-s_09* "**********")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-sla-t_00* "**********")
(defparameter *aa-sla-t_01* "//////////")
(defparameter *aa-sla-t_02* "///_|/////")
(defparameter *aa-sla-t_03* "/_|_|_|_|/")
(defparameter *aa-sla-t_04* "///_|/////")
(defparameter *aa-sla-t_05* "///_|/////")
(defparameter *aa-sla-t_06* "/////_|_|/")
(defparameter *aa-sla-t_07* "//////////")
(defparameter *aa-sla-t_08* "//////////")
(defparameter *aa-sla-t_09* "**********")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-sla-u_00* "**********")
(defparameter *aa-sla-u_01* "//////////")
(defparameter *aa-sla-u_02* "//////////")
(defparameter *aa-sla-u_03* "/_|////_|/")
(defparameter *aa-sla-u_04* "/_|////_|/")
(defparameter *aa-sla-u_05* "/_|////_|/")
(defparameter *aa-sla-u_06* "///_|_|_|/")
(defparameter *aa-sla-u_07* "//////////")
(defparameter *aa-sla-u_08* "//////////")
(defparameter *aa-sla-u_09* "**********")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-sla-v_00* "***************")
(defparameter *aa-sla-v_01* "///////////////")
(defparameter *aa-sla-v_02* "///////////////")
(defparameter *aa-sla-v_03* "//_|////////_|/")
(defparameter *aa-sla-v_04* "///_|//////_|//")
(defparameter *aa-sla-v_05* "/////_|//_|////")
(defparameter *aa-sla-v_06* "///////_|//////")
(defparameter *aa-sla-v_07* "///////////////")
(defparameter *aa-sla-v_08* "///////////////")
(defparameter *aa-sla-v_09* "***************")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-sla-w_00* "********************")
(defparameter *aa-sla-w_01* "////////////////////")
(defparameter *aa-sla-w_02* "////////////////////")
(defparameter *aa-sla-w_03* "/_|//////_|//////_|/")
(defparameter *aa-sla-w_04* "//_|/////_|/////_|//")
(defparameter *aa-sla-w_05* "///_|//_|//_|//_|///")
(defparameter *aa-sla-w_06* "/////_|//////_|/////")
(defparameter *aa-sla-w_07* "////////////////////")
(defparameter *aa-sla-w_08* "////////////////////")
(defparameter *aa-sla-w_09* "********************")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-sla-x_00* "***********")
(defparameter *aa-sla-x_01* "///////////")
(defparameter *aa-sla-x_02* "///////////")
(defparameter *aa-sla-x_03* "//_|////_|/")
(defparameter *aa-sla-x_04* "////_|_|///")
(defparameter *aa-sla-x_05* "////_|_|///")
(defparameter *aa-sla-x_06* "//_|////_|/")
(defparameter *aa-sla-x_07* "///////////")
(defparameter *aa-sla-x_08* "///////////")
(defparameter *aa-sla-x_09* "***********")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-sla-y_00* "**********")
(defparameter *aa-sla-y_01* "//////////")
(defparameter *aa-sla-y_02* "//////////")
(defparameter *aa-sla-y_03* "/_|////_|/")
(defparameter *aa-sla-y_04* "/_|////_|/")
(defparameter *aa-sla-y_05* "/_|////_|/")
(defparameter *aa-sla-y_06* "///_|_|_|/")
(defparameter *aa-sla-y_07* "///////_|/")
(defparameter *aa-sla-y_08* "///_|_|///")
(defparameter *aa-sla-y_09* "**********")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-sla-z_00* "***********")
(defparameter *aa-sla-z_01* "///////////")
(defparameter *aa-sla-z_02* "///////////")
(defparameter *aa-sla-z_03* "//_|_|_|_|/")
(defparameter *aa-sla-z_04* "//////_|///")
(defparameter *aa-sla-z_05* "////_|/////")
(defparameter *aa-sla-z_06* "//_|_|_|_|/")
(defparameter *aa-sla-z_07* "///////////")
(defparameter *aa-sla-z_08* "///////////")
(defparameter *aa-sla-z_09* "***********")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-sla-La_00* "**********")
(defparameter *aa-sla-La_01* "//////////")
(defparameter *aa-sla-La_02* "///_|_|///")
(defparameter *aa-sla-La_03* "/_|////_|/")
(defparameter *aa-sla-La_04* "/_|_|_|_|/")
(defparameter *aa-sla-La_05* "/_|////_|/")
(defparameter *aa-sla-La_06* "/_|////_|/")
(defparameter *aa-sla-La_07* "//////////")
(defparameter *aa-sla-La_08* "//////////")
(defparameter *aa-sla-La_09* "**********")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-sla-Lb_00* "**********")
(defparameter *aa-sla-Lb_01* "//////////")
(defparameter *aa-sla-Lb_02* "/_|_|_|///")
(defparameter *aa-sla-Lb_03* "/_|////_|/")
(defparameter *aa-sla-Lb_04* "/_|_|_|///")
(defparameter *aa-sla-Lb_05* "/_|////_|/")
(defparameter *aa-sla-Lb_06* "/_|_|_|///")
(defparameter *aa-sla-Lb_07* "//////////")
(defparameter *aa-sla-Lb_08* "//////////")
(defparameter *aa-sla-Lb_09* "**********")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-sla-Lc_00* "**********")
(defparameter *aa-sla-Lc_01* "//////////")
(defparameter *aa-sla-Lc_02* "///_|_|_|/")
(defparameter *aa-sla-Lc_03* "/_|///////")
(defparameter *aa-sla-Lc_04* "/_|///////")
(defparameter *aa-sla-Lc_05* "/_|///////")
(defparameter *aa-sla-Lc_06* "///_|_|_|/")
(defparameter *aa-sla-Lc_07* "//////////")
(defparameter *aa-sla-Lc_08* "//////////")
(defparameter *aa-sla-Lc_09* "**********")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-sla-Ld_00* "**********")
(defparameter *aa-sla-Ld_01* "//////////")
(defparameter *aa-sla-Ld_02* "/_|_|_|///")
(defparameter *aa-sla-Ld_03* "/_|////_|/")
(defparameter *aa-sla-Ld_04* "/_|////_|/")
(defparameter *aa-sla-Ld_05* "/_|////_|/")
(defparameter *aa-sla-Ld_06* "/_|_|_|///")
(defparameter *aa-sla-Ld_07* "//////////")
(defparameter *aa-sla-Ld_08* "//////////")
(defparameter *aa-sla-Ld_09* "**********")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-sla-Le_00* "**********")
(defparameter *aa-sla-Le_01* "//////////")
(defparameter *aa-sla-Le_02* "/_|_|_|_|/")
(defparameter *aa-sla-Le_03* "/_|///////")
(defparameter *aa-sla-Le_04* "/_|_|_|///")
(defparameter *aa-sla-Le_05* "/_|///////")
(defparameter *aa-sla-Le_06* "/_|_|_|_|/")
(defparameter *aa-sla-Le_07* "//////////")
(defparameter *aa-sla-Le_08* "//////////")
(defparameter *aa-sla-Le_09* "**********")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-sla-Lf_00* "**********")
(defparameter *aa-sla-Lf_01* "//////////")
(defparameter *aa-sla-Lf_02* "/_|_|_|_|/")
(defparameter *aa-sla-Lf_03* "/_|///////")
(defparameter *aa-sla-Lf_04* "/_|_|_|///")
(defparameter *aa-sla-Lf_05* "/_|///////")
(defparameter *aa-sla-Lf_06* "/_|///////")
(defparameter *aa-sla-Lf_07* "//////////")
(defparameter *aa-sla-Lf_08* "//////////")
(defparameter *aa-sla-Lf_09* "**********")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-sla-Lg_00* "**********")
(defparameter *aa-sla-Lg_01* "//////////")
(defparameter *aa-sla-Lg_02* "///_|_|_|/")
(defparameter *aa-sla-Lg_03* "/_|///////")
(defparameter *aa-sla-Lg_04* "/_|//_|_|/")
(defparameter *aa-sla-Lg_05* "/_|////_|/")
(defparameter *aa-sla-Lg_06* "///_|_|_|/")
(defparameter *aa-sla-Lg_07* "//////////")
(defparameter *aa-sla-Lg_08* "//////////")
(defparameter *aa-sla-Lg_09* "**********")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-sla-Lh_00* "**********")
(defparameter *aa-sla-Lh_01* "//////////")
(defparameter *aa-sla-Lh_02* "/_|////_|/")
(defparameter *aa-sla-Lh_03* "/_|////_|/")
(defparameter *aa-sla-Lh_04* "/_|_|_|_|/")
(defparameter *aa-sla-Lh_05* "/_|////_|/")
(defparameter *aa-sla-Lh_06* "/_|////_|/")
(defparameter *aa-sla-Lh_07* "//////////")
(defparameter *aa-sla-Lh_08* "//////////")
(defparameter *aa-sla-Lh_09* "**********")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-sla-Li_00* "********")
(defparameter *aa-sla-Li_01* "////////")
(defparameter *aa-sla-Li_02* "/_|_|_|/")
(defparameter *aa-sla-Li_03* "///_|///")
(defparameter *aa-sla-Li_04* "///_|///")
(defparameter *aa-sla-Li_05* "///_|///")
(defparameter *aa-sla-Li_06* "/_|_|_|/")
(defparameter *aa-sla-Li_07* "////////")
(defparameter *aa-sla-Li_08* "////////")
(defparameter *aa-sla-Li_09* "********")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-sla-Lj_00* "**********")
(defparameter *aa-sla-Lj_01* "//////////")
(defparameter *aa-sla-Lj_02* "///////_|/")
(defparameter *aa-sla-Lj_03* "///////_|/")
(defparameter *aa-sla-Lj_04* "///////_|/")
(defparameter *aa-sla-Lj_05* "/_|////_|/")
(defparameter *aa-sla-Lj_06* "///_|_|///")
(defparameter *aa-sla-Lj_07* "//////////")
(defparameter *aa-sla-Lj_08* "//////////")
(defparameter *aa-sla-Lj_09* "**********")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-sla-Lk_00* "**********")
(defparameter *aa-sla-Lk_01* "//////////")
(defparameter *aa-sla-Lk_02* "/_|////_|/")
(defparameter *aa-sla-Lk_03* "/_|//_|///")
(defparameter *aa-sla-Lk_04* "/_|_|/////")
(defparameter *aa-sla-Lk_05* "/_|//_|///")
(defparameter *aa-sla-Lk_06* "/_|////_|/")
(defparameter *aa-sla-Lk_07* "//////////")
(defparameter *aa-sla-Lk_08* "//////////")
(defparameter *aa-sla-Lk_09* "**********")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-sla-Ll_00* "**********")
(defparameter *aa-sla-Ll_01* "//////////")
(defparameter *aa-sla-Ll_02* "/_|///////")
(defparameter *aa-sla-Ll_03* "/_|///////")
(defparameter *aa-sla-Ll_04* "/_|///////")
(defparameter *aa-sla-Ll_05* "/_|///////")
(defparameter *aa-sla-Ll_06* "/_|_|_|_|/")
(defparameter *aa-sla-Ll_07* "//////////")
(defparameter *aa-sla-Ll_08* "//////////")
(defparameter *aa-sla-Ll_09* "**********")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-sla-Lm_00* "***********")
(defparameter *aa-sla-Lm_01* "///////////")
(defparameter *aa-sla-Lm_02* "_|//////_|/")
(defparameter *aa-sla-Lm_03* "_|_|//_|_|/")
(defparameter *aa-sla-Lm_04* "_|//_|//_|/")
(defparameter *aa-sla-Lm_05* "_|//////_|/")
(defparameter *aa-sla-Lm_06* "_|//////_|/")
(defparameter *aa-sla-Lm_07* "///////////")
(defparameter *aa-sla-Lm_08* "///////////")
(defparameter *aa-sla-Lm_09* "***********")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-sla-Ln_00* "*************")
(defparameter *aa-sla-Ln_01* "/////////////")
(defparameter *aa-sla-Ln_02* "//_|//////_|/")
(defparameter *aa-sla-Ln_03* "//_|_|////_|/")
(defparameter *aa-sla-Ln_04* "//_|//_|//_|/")
(defparameter *aa-sla-Ln_05* "//_|////_|_|/")
(defparameter *aa-sla-Ln_06* "//_|//////_|/")
(defparameter *aa-sla-Ln_07* "/////////////")
(defparameter *aa-sla-Ln_08* "/////////////")
(defparameter *aa-sla-Ln_09* "*************")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-sla-Lo_00* "**********")
(defparameter *aa-sla-Lo_01* "//////////")
(defparameter *aa-sla-Lo_02* "///_|_|///")
(defparameter *aa-sla-Lo_03* "/_|////_|/")
(defparameter *aa-sla-Lo_04* "/_|////_|/")
(defparameter *aa-sla-Lo_05* "/_|////_|/")
(defparameter *aa-sla-Lo_06* "///_|_|///")
(defparameter *aa-sla-Lo_07* "//////////")
(defparameter *aa-sla-Lo_08* "//////////")
(defparameter *aa-sla-Lo_09* "**********")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-sla-Lp_00* "**********")
(defparameter *aa-sla-Lp_01* "//////////")
(defparameter *aa-sla-Lp_02* "/_|_|_|///")
(defparameter *aa-sla-Lp_03* "/_|////_|/")
(defparameter *aa-sla-Lp_04* "/_|_|_|///")
(defparameter *aa-sla-Lp_05* "/_|///////")
(defparameter *aa-sla-Lp_06* "/_|///////")
(defparameter *aa-sla-Lp_07* "//////////")
(defparameter *aa-sla-Lp_08* "//////////")
(defparameter *aa-sla-Lp_09* "**********")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-sla-Lq_00* "************")
(defparameter *aa-sla-Lq_01* "////////////")
(defparameter *aa-sla-Lq_02* "///_|_|/////")
(defparameter *aa-sla-Lq_03* "/_|////_|///")
(defparameter *aa-sla-Lq_04* "/_|//_|_|///")
(defparameter *aa-sla-Lq_05* "/_|////_|///")
(defparameter *aa-sla-Lq_06* "///_|_|//_|/")
(defparameter *aa-sla-Lq_07* "////////////")
(defparameter *aa-sla-Lq_08* "////////////")
(defparameter *aa-sla-Lq_09* "************")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-sla-Lr_00* "**********")
(defparameter *aa-sla-Lr_01* "//////////")
(defparameter *aa-sla-Lr_02* "/_|_|_|///")
(defparameter *aa-sla-Lr_03* "/_|////_|/")
(defparameter *aa-sla-Lr_04* "/_|_|_|///")
(defparameter *aa-sla-Lr_05* "/_|////_|/")
(defparameter *aa-sla-Lr_06* "/_|////_|/")
(defparameter *aa-sla-Lr_07* "//////////")
(defparameter *aa-sla-Lr_08* "//////////")
(defparameter *aa-sla-Lr_09* "**********")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-sla-Ls_00* "**********")
(defparameter *aa-sla-Ls_01* "//////////")
(defparameter *aa-sla-Ls_02* "///_|_|_|/")
(defparameter *aa-sla-Ls_03* "/_|///////")
(defparameter *aa-sla-Ls_04* "///_|_|///")
(defparameter *aa-sla-Ls_05* "///////_|/")
(defparameter *aa-sla-Ls_06* "/_|_|_|///")
(defparameter *aa-sla-Ls_07* "//////////")
(defparameter *aa-sla-Ls_08* "//////////")
(defparameter *aa-sla-Ls_09* "**********")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-sla-Lt_00* "************")
(defparameter *aa-sla-Lt_01* "////////////")
(defparameter *aa-sla-Lt_02* "/_|_|_|_|_|/")
(defparameter *aa-sla-Lt_03* "/////_|/////")
(defparameter *aa-sla-Lt_04* "/////_|/////")
(defparameter *aa-sla-Lt_05* "/////_|/////")
(defparameter *aa-sla-Lt_06* "/////_|/////")
(defparameter *aa-sla-Lt_07* "////////////")
(defparameter *aa-sla-Lt_08* "////////////")
(defparameter *aa-sla-Lt_09* "************")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-sla-Lu_00* "**********")
(defparameter *aa-sla-Lu_01* "//////////")
(defparameter *aa-sla-Lu_02* "/_|////_|/")
(defparameter *aa-sla-Lu_03* "/_|////_|/")
(defparameter *aa-sla-Lu_04* "/_|////_|/")
(defparameter *aa-sla-Lu_05* "/_|////_|/")
(defparameter *aa-sla-Lu_06* "///_|_|///")
(defparameter *aa-sla-Lu_07* "//////////")
(defparameter *aa-sla-Lu_08* "//////////")
(defparameter *aa-sla-Lu_09* "**********")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-sla-Lv_00* "***************")
(defparameter *aa-sla-Lv_01* "///////////////")
(defparameter *aa-sla-Lv_02* "/_|/////////_|/")
(defparameter *aa-sla-Lv_03* "//_|///////_|//")
(defparameter *aa-sla-Lv_04* "///_|/////_|///")
(defparameter *aa-sla-Lv_05* "/////_|//_|////")
(defparameter *aa-sla-Lv_06* "///////_|//////")
(defparameter *aa-sla-Lv_07* "///////////////")
(defparameter *aa-sla-Lv_08* "///////////////")
(defparameter *aa-sla-Lv_09* "***************")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-sla-Lw_00* "****************")
(defparameter *aa-sla-Lw_01* "////////////////")
(defparameter *aa-sla-Lw_02* "/_|//////////_|/")
(defparameter *aa-sla-Lw_03* "/_|//////////_|/")
(defparameter *aa-sla-Lw_04* "/_|////_|////_|/")
(defparameter *aa-sla-Lw_05* "///_|//_|//_|///")
(defparameter *aa-sla-Lw_06* "/////_|//_|/////")
(defparameter *aa-sla-Lw_07* "////////////////")
(defparameter *aa-sla-Lw_08* "////////////////")
(defparameter *aa-sla-Lw_09* "****************")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-sla-Lx_00* "************")
(defparameter *aa-sla-Lx_01* "////////////")
(defparameter *aa-sla-Lx_02* "/_|//////_|/")
(defparameter *aa-sla-Lx_03* "///_|//_|///")
(defparameter *aa-sla-Lx_04* "/////_|/////")
(defparameter *aa-sla-Lx_05* "///_|//_|///")
(defparameter *aa-sla-Lx_06* "/_|//////_|/")
(defparameter *aa-sla-Lx_07* "////////////")
(defparameter *aa-sla-Lx_08* "////////////")
(defparameter *aa-sla-Lx_09* "************")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-sla-Ly_00* "************")
(defparameter *aa-sla-Ly_01* "////////////")
(defparameter *aa-sla-Ly_02* "/_|//////_|/")
(defparameter *aa-sla-Ly_03* "///_|//_|///")
(defparameter *aa-sla-Ly_04* "/////_|/////")
(defparameter *aa-sla-Ly_05* "/////_|/////")
(defparameter *aa-sla-Ly_06* "/////_|/////")
(defparameter *aa-sla-Ly_07* "////////////")
(defparameter *aa-sla-Ly_08* "////////////")
(defparameter *aa-sla-Ly_09* "************")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-sla-Lz_00* "************")
(defparameter *aa-sla-Lz_01* "////////////")
(defparameter *aa-sla-Lz_02* "/_|_|_|_|_|/")
(defparameter *aa-sla-Lz_03* "///////_|///")
(defparameter *aa-sla-Lz_04* "/////_|/////")
(defparameter *aa-sla-Lz_05* "///_|///////")
(defparameter *aa-sla-Lz_06* "/_|_|_|_|_|/")
(defparameter *aa-sla-Lz_07* "////////////")
(defparameter *aa-sla-Lz_08* "////////////")
(defparameter *aa-sla-Lz_09* "************")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-sla-dot_00* "****")
(defparameter *aa-sla-dot_01* "////")
(defparameter *aa-sla-dot_02* "////")
(defparameter *aa-sla-dot_03* "////")
(defparameter *aa-sla-dot_04* "////")
(defparameter *aa-sla-dot_05* "////")
(defparameter *aa-sla-dot_06* "/_|/")
(defparameter *aa-sla-dot_07* "////")
(defparameter *aa-sla-dot_08* "////")
(defparameter *aa-sla-dot_09* "****")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-sla-Question_00* "********")
(defparameter *aa-sla-Question_01* "////////")
(defparameter *aa-sla-Question_02* "/_|_|///")
(defparameter *aa-sla-Question_03* "/////_|/")
(defparameter *aa-sla-Question_04* "/_|_|///")
(defparameter *aa-sla-Question_05* "////////")
(defparameter *aa-sla-Question_06* "/_|/////")
(defparameter *aa-sla-Question_07* "////////")
(defparameter *aa-sla-Question_08* "////////")
(defparameter *aa-sla-Question_09* "********")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-sla-exc_00* "****")
(defparameter *aa-sla-exc_01* "////")
(defparameter *aa-sla-exc_02* "/_|/")
(defparameter *aa-sla-exc_03* "/_|/")
(defparameter *aa-sla-exc_04* "/_|/")
(defparameter *aa-sla-exc_05* "////")
(defparameter *aa-sla-exc_06* "/_|/")
(defparameter *aa-sla-exc_07* "////")
(defparameter *aa-sla-exc_08* "////")
(defparameter *aa-sla-exc_09* "****")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-sla-hyphen_00* "************")
(defparameter *aa-sla-hyphen_01* "////////////")
(defparameter *aa-sla-hyphen_02* "////////////")
(defparameter *aa-sla-hyphen_03* "////////////")
(defparameter *aa-sla-hyphen_04* "/_|_|_|_|_|/")
(defparameter *aa-sla-hyphen_05* "////////////")
(defparameter *aa-sla-hyphen_06* "////////////")
(defparameter *aa-sla-hyphen_07* "////////////")
(defparameter *aa-sla-hyphen_08* "////////////")
(defparameter *aa-sla-hyphen_09* "************")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
(defparameter *aa-sla-Space_00* "****")
(defparameter *aa-sla-Space_01* "////")
(defparameter *aa-sla-Space_02* "////")
(defparameter *aa-sla-Space_03* "////")
(defparameter *aa-sla-Space_04* "////")
(defparameter *aa-sla-Space_05* "////")
(defparameter *aa-sla-Space_06* "////")
(defparameter *aa-sla-Space_07* "////")
(defparameter *aa-sla-Space_08* "////")
(defparameter *aa-sla-Space_09* "****")
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;}}}
; *aa-nodes*{{{
(defparameter *aa-nodes* '((#\0   *aa-0_00*   *aa-0_01*   *aa-0_02*   *aa-0_03*   *aa-0_04*   *aa-0_05*   *aa-0_06*   *aa-0_07*  )
                           (#\1   *aa-1_00*   *aa-1_01*   *aa-1_02*   *aa-1_03*   *aa-1_04*   *aa-1_05*   *aa-1_06*   *aa-1_07*  )
                           (#\2   *aa-2_00*   *aa-2_01*   *aa-2_02*   *aa-2_03*   *aa-2_04*   *aa-2_05*   *aa-2_06*   *aa-2_07*  )
                           (#\3   *aa-3_00*   *aa-3_01*   *aa-3_02*   *aa-3_03*   *aa-3_04*   *aa-3_05*   *aa-3_06*   *aa-3_07*  )
                           (#\4   *aa-4_00*   *aa-4_01*   *aa-4_02*   *aa-4_03*   *aa-4_04*   *aa-4_05*   *aa-4_06*   *aa-4_07*  )
                           (#\5   *aa-5_00*   *aa-5_01*   *aa-5_02*   *aa-5_03*   *aa-5_04*   *aa-5_05*   *aa-5_06*   *aa-5_07*  )
                           (#\6   *aa-6_00*   *aa-6_01*   *aa-6_02*   *aa-6_03*   *aa-6_04*   *aa-6_05*   *aa-6_06*   *aa-6_07*  )
                           (#\7   *aa-7_00*   *aa-7_01*   *aa-7_02*   *aa-7_03*   *aa-7_04*   *aa-7_05*   *aa-7_06*   *aa-7_07*  )
                           (#\8   *aa-8_00*   *aa-8_01*   *aa-8_02*   *aa-8_03*   *aa-8_04*   *aa-8_05*   *aa-8_06*   *aa-8_07*  )
                           (#\9   *aa-9_00*   *aa-9_01*   *aa-9_02*   *aa-9_03*   *aa-9_04*   *aa-9_05*   *aa-9_06*   *aa-9_07*  )
                           (#\a   *aa-a_00*   *aa-a_01*   *aa-a_02*   *aa-a_03*   *aa-a_04*   *aa-a_05*   *aa-a_06*   *aa-a_07*  )
                           (#\b   *aa-b_00*   *aa-b_01*   *aa-b_02*   *aa-b_03*   *aa-b_04*   *aa-b_05*   *aa-b_06*   *aa-b_07*  )
                           (#\c   *aa-c_00*   *aa-c_01*   *aa-c_02*   *aa-c_03*   *aa-c_04*   *aa-c_05*   *aa-c_06*   *aa-c_07*  )
                           (#\d   *aa-d_00*   *aa-d_01*   *aa-d_02*   *aa-d_03*   *aa-d_04*   *aa-d_05*   *aa-d_06*   *aa-d_07*  )
                           (#\e   *aa-e_00*   *aa-e_01*   *aa-e_02*   *aa-e_03*   *aa-e_04*   *aa-e_05*   *aa-e_06*   *aa-e_07*  )
                           (#\f   *aa-f_00*   *aa-f_01*   *aa-f_02*   *aa-f_03*   *aa-f_04*   *aa-f_05*   *aa-f_06*   *aa-f_07*  )
                           (#\g   *aa-g_00*   *aa-g_01*   *aa-g_02*   *aa-g_03*   *aa-g_04*   *aa-g_05*   *aa-g_06*   *aa-g_07*  )
                           (#\h   *aa-h_00*   *aa-h_01*   *aa-h_02*   *aa-h_03*   *aa-h_04*   *aa-h_05*   *aa-h_06*   *aa-h_07*  )
                           (#\i   *aa-i_00*   *aa-i_01*   *aa-i_02*   *aa-i_03*   *aa-i_04*   *aa-i_05*   *aa-i_06*   *aa-i_07*  )
                           (#\j   *aa-j_00*   *aa-j_01*   *aa-j_02*   *aa-j_03*   *aa-j_04*   *aa-j_05*   *aa-j_06*   *aa-j_07*  )
                           (#\k   *aa-k_00*   *aa-k_01*   *aa-k_02*   *aa-k_03*   *aa-k_04*   *aa-k_05*   *aa-k_06*   *aa-k_07*  )
                           (#\l   *aa-l_00*   *aa-l_01*   *aa-l_02*   *aa-l_03*   *aa-l_04*   *aa-l_05*   *aa-l_06*   *aa-l_07*  )
                           (#\m   *aa-m_00*   *aa-m_01*   *aa-m_02*   *aa-m_03*   *aa-m_04*   *aa-m_05*   *aa-m_06*   *aa-m_07*  )
                           (#\n   *aa-n_00*   *aa-n_01*   *aa-n_02*   *aa-n_03*   *aa-n_04*   *aa-n_05*   *aa-n_06*   *aa-n_07*  )
                           (#\o   *aa-o_00*   *aa-o_01*   *aa-o_02*   *aa-o_03*   *aa-o_04*   *aa-o_05*   *aa-o_06*   *aa-o_07*  )
                           (#\p   *aa-p_00*   *aa-p_01*   *aa-p_02*   *aa-p_03*   *aa-p_04*   *aa-p_05*   *aa-p_06*   *aa-p_07*  )
                           (#\q   *aa-q_00*   *aa-q_01*   *aa-q_02*   *aa-q_03*   *aa-q_04*   *aa-q_05*   *aa-q_06*   *aa-q_07*  )
                           (#\r   *aa-r_00*   *aa-r_01*   *aa-r_02*   *aa-r_03*   *aa-r_04*   *aa-r_05*   *aa-r_06*   *aa-r_07*  )
                           (#\s   *aa-s_00*   *aa-s_01*   *aa-s_02*   *aa-s_03*   *aa-s_04*   *aa-s_05*   *aa-s_06*   *aa-s_07*  )
                           (#\t   *aa-t_00*   *aa-t_01*   *aa-t_02*   *aa-t_03*   *aa-t_04*   *aa-t_05*   *aa-t_06*   *aa-t_07*  )
                           (#\u   *aa-u_00*   *aa-u_01*   *aa-u_02*   *aa-u_03*   *aa-u_04*   *aa-u_05*   *aa-u_06*   *aa-u_07*  )
                           (#\v   *aa-v_00*   *aa-v_01*   *aa-v_02*   *aa-v_03*   *aa-v_04*   *aa-v_05*   *aa-v_06*   *aa-v_07*  )
                           (#\w   *aa-w_00*   *aa-w_01*   *aa-w_02*   *aa-w_03*   *aa-w_04*   *aa-w_05*   *aa-w_06*   *aa-w_07*  )
                           (#\x   *aa-x_00*   *aa-x_01*   *aa-x_02*   *aa-x_03*   *aa-x_04*   *aa-x_05*   *aa-x_06*   *aa-x_07*  )
                           (#\y   *aa-y_00*   *aa-y_01*   *aa-y_02*   *aa-y_03*   *aa-y_04*   *aa-y_05*   *aa-y_06*   *aa-y_07*  )
                           (#\z   *aa-z_00*   *aa-z_01*   *aa-z_02*   *aa-z_03*   *aa-z_04*   *aa-z_05*   *aa-z_06*   *aa-z_07*  )
                           (#\A  *aa-La_00*  *aa-La_01*  *aa-La_02*  *aa-La_03*  *aa-La_04*  *aa-La_05*  *aa-La_06*  *aa-La_07*  )
                           (#\B  *aa-Lb_00*  *aa-Lb_01*  *aa-Lb_02*  *aa-Lb_03*  *aa-Lb_04*  *aa-Lb_05*  *aa-Lb_06*  *aa-Lb_07*  )
                           (#\C  *aa-Lc_00*  *aa-Lc_01*  *aa-Lc_02*  *aa-Lc_03*  *aa-Lc_04*  *aa-Lc_05*  *aa-Lc_06*  *aa-Lc_07*  )
                           (#\D  *aa-Ld_00*  *aa-Ld_01*  *aa-Ld_02*  *aa-Ld_03*  *aa-Ld_04*  *aa-Ld_05*  *aa-Ld_06*  *aa-Ld_07*  )
                           (#\E  *aa-Le_00*  *aa-Le_01*  *aa-Le_02*  *aa-Le_03*  *aa-Le_04*  *aa-Le_05*  *aa-Le_06*  *aa-Le_07*  )
                           (#\F  *aa-Lf_00*  *aa-Lf_01*  *aa-Lf_02*  *aa-Lf_03*  *aa-Lf_04*  *aa-Lf_05*  *aa-Lf_06*  *aa-Lf_07*  )
                           (#\G  *aa-Lg_00*  *aa-Lg_01*  *aa-Lg_02*  *aa-Lg_03*  *aa-Lg_04*  *aa-Lg_05*  *aa-Lg_06*  *aa-Lg_07*  )
                           (#\H  *aa-Lh_00*  *aa-Lh_01*  *aa-Lh_02*  *aa-Lh_03*  *aa-Lh_04*  *aa-Lh_05*  *aa-Lh_06*  *aa-Lh_07*  )
                           (#\I  *aa-Li_00*  *aa-Li_01*  *aa-Li_02*  *aa-Li_03*  *aa-Li_04*  *aa-Li_05*  *aa-Li_06*  *aa-Li_07*  )
                           (#\J  *aa-Lj_00*  *aa-Lj_01*  *aa-Lj_02*  *aa-Lj_03*  *aa-Lj_04*  *aa-Lj_05*  *aa-Lj_06*  *aa-Lj_07*  )
                           (#\K  *aa-Lk_00*  *aa-Lk_01*  *aa-Lk_02*  *aa-Lk_03*  *aa-Lk_04*  *aa-Lk_05*  *aa-Lk_06*  *aa-Lk_07*  )
                           (#\L  *aa-Ll_00*  *aa-Ll_01*  *aa-Ll_02*  *aa-Ll_03*  *aa-Ll_04*  *aa-Ll_05*  *aa-Ll_06*  *aa-Ll_07*  )
                           (#\M  *aa-Lm_00*  *aa-Lm_01*  *aa-Lm_02*  *aa-Lm_03*  *aa-Lm_04*  *aa-Lm_05*  *aa-Lm_06*  *aa-Lm_07*  )
                           (#\N  *aa-Ln_00*  *aa-Ln_01*  *aa-Ln_02*  *aa-Ln_03*  *aa-Ln_04*  *aa-Ln_05*  *aa-Ln_06*  *aa-Ln_07*  )
                           (#\O  *aa-Lo_00*  *aa-Lo_01*  *aa-Lo_02*  *aa-Lo_03*  *aa-Lo_04*  *aa-Lo_05*  *aa-Lo_06*  *aa-Lo_07*  )
                           (#\P  *aa-Lp_00*  *aa-Lp_01*  *aa-Lp_02*  *aa-Lp_03*  *aa-Lp_04*  *aa-Lp_05*  *aa-Lp_06*  *aa-Lp_07*  )
                           (#\Q  *aa-Lq_00*  *aa-Lq_01*  *aa-Lq_02*  *aa-Lq_03*  *aa-Lq_04*  *aa-Lq_05*  *aa-Lq_06*  *aa-Lq_07*  )
                           (#\R  *aa-Lr_00*  *aa-Lr_01*  *aa-Lr_02*  *aa-Lr_03*  *aa-Lr_04*  *aa-Lr_05*  *aa-Lr_06*  *aa-Lr_07*  )
                           (#\S  *aa-Ls_00*  *aa-Ls_01*  *aa-Ls_02*  *aa-Ls_03*  *aa-Ls_04*  *aa-Ls_05*  *aa-Ls_06*  *aa-Ls_07*  )
                           (#\T  *aa-Lt_00*  *aa-Lt_01*  *aa-Lt_02*  *aa-Lt_03*  *aa-Lt_04*  *aa-Lt_05*  *aa-Lt_06*  *aa-Lt_07*  )
                           (#\U  *aa-Lu_00*  *aa-Lu_01*  *aa-Lu_02*  *aa-Lu_03*  *aa-Lu_04*  *aa-Lu_05*  *aa-Lu_06*  *aa-Lu_07*  )
                           (#\V  *aa-Lv_00*  *aa-Lv_01*  *aa-Lv_02*  *aa-Lv_03*  *aa-Lv_04*  *aa-Lv_05*  *aa-Lv_06*  *aa-Lv_07*  )
                           (#\W  *aa-Lw_00*  *aa-Lw_01*  *aa-Lw_02*  *aa-Lw_03*  *aa-Lw_04*  *aa-Lw_05*  *aa-Lw_06*  *aa-Lw_07*  )
                           (#\X  *aa-Lx_00*  *aa-Lx_01*  *aa-Lx_02*  *aa-Lx_03*  *aa-Lx_04*  *aa-Lx_05*  *aa-Lx_06*  *aa-Lx_07*  )
                           (#\Y  *aa-Ly_00*  *aa-Ly_01*  *aa-Ly_02*  *aa-Ly_03*  *aa-Ly_04*  *aa-Ly_05*  *aa-Ly_06*  *aa-Ly_07*  )
                           (#\Z  *aa-Lz_00*  *aa-Lz_01*  *aa-Lz_02*  *aa-Lz_03*  *aa-Lz_04*  *aa-Lz_05*  *aa-Lz_06*  *aa-Lz_07*  )
                           (#\. *aa-dot_00* *aa-dot_01* *aa-dot_02* *aa-dot_03* *aa-dot_04* *aa-dot_05* *aa-dot_06* *aa-dot_07*)
                           (#\! *aa-exc_00* *aa-exc_01* *aa-exc_02* *aa-exc_03* *aa-exc_04* *aa-exc_05* *aa-exc_06* *aa-exc_07*)
                           (#\? *aa-Question_00* *aa-Question_01* *aa-Question_02* *aa-Question_03* *aa-Question_04* *aa-Question_05* *aa-Question_06* *aa-Question_07*)
                           (#\- *aa-hyphen_00* *aa-hyphen_01* *aa-hyphen_02* *aa-hyphen_03* *aa-hyphen_04* *aa-hyphen_05* *aa-hyphen_06* *aa-hyphen_07*)
                           (#\Space *aa-Space_00* *aa-Space_01* *aa-Space_02* *aa-Space_03* *aa-Space_04* *aa-Space_05* *aa-Space_06* *aa-Space_07*)))
;}}}
; *aa-Slash-nodes*{{{
(defparameter *aa-Slash-nodes* '((#\0 *aa-sla-0_00* *aa-sla-0_01* *aa-sla-0_02* *aa-sla-0_03* *aa-sla-0_04* *aa-sla-0_05* *aa-sla-0_06* *aa-sla-0_07* *aa-sla-0_08* *aa-sla-0_09*)
                                 (#\1 *aa-sla-1_00* *aa-sla-1_01* *aa-sla-1_02* *aa-sla-1_03* *aa-sla-1_04* *aa-sla-1_05* *aa-sla-1_06* *aa-sla-1_07* *aa-sla-1_08* *aa-sla-1_09*)
                                 (#\2 *aa-sla-2_00* *aa-sla-2_01* *aa-sla-2_02* *aa-sla-2_03* *aa-sla-2_04* *aa-sla-2_05* *aa-sla-2_06* *aa-sla-2_07* *aa-sla-2_08* *aa-sla-2_09*)
                                 (#\3 *aa-sla-3_00* *aa-sla-3_01* *aa-sla-3_02* *aa-sla-3_03* *aa-sla-3_04* *aa-sla-3_05* *aa-sla-3_06* *aa-sla-3_07* *aa-sla-3_08* *aa-sla-3_09*)
                                 (#\4 *aa-sla-4_00* *aa-sla-4_01* *aa-sla-4_02* *aa-sla-4_03* *aa-sla-4_04* *aa-sla-4_05* *aa-sla-4_06* *aa-sla-4_07* *aa-sla-4_08* *aa-sla-4_09*)
                                 (#\5 *aa-sla-5_00* *aa-sla-5_01* *aa-sla-5_02* *aa-sla-5_03* *aa-sla-5_04* *aa-sla-5_05* *aa-sla-5_06* *aa-sla-5_07* *aa-sla-5_08* *aa-sla-5_09*)
                                 (#\6 *aa-sla-6_00* *aa-sla-6_01* *aa-sla-6_02* *aa-sla-6_03* *aa-sla-6_04* *aa-sla-6_05* *aa-sla-6_06* *aa-sla-6_07* *aa-sla-6_08* *aa-sla-6_09*)
                                 (#\7 *aa-sla-7_00* *aa-sla-7_01* *aa-sla-7_02* *aa-sla-7_03* *aa-sla-7_04* *aa-sla-7_05* *aa-sla-7_06* *aa-sla-7_07* *aa-sla-7_08* *aa-sla-7_09*)
                                 (#\8 *aa-sla-8_00* *aa-sla-8_01* *aa-sla-8_02* *aa-sla-8_03* *aa-sla-8_04* *aa-sla-8_05* *aa-sla-8_06* *aa-sla-8_07* *aa-sla-8_08* *aa-sla-8_09*)
                                 (#\9 *aa-sla-9_00* *aa-sla-9_01* *aa-sla-9_02* *aa-sla-9_03* *aa-sla-9_04* *aa-sla-9_05* *aa-sla-9_06* *aa-sla-9_07* *aa-sla-9_08* *aa-sla-9_09*)
                                 (#\a *aa-sla-a_00* *aa-sla-a_01* *aa-sla-a_02* *aa-sla-a_03* *aa-sla-a_04* *aa-sla-a_05* *aa-sla-a_06* *aa-sla-a_07* *aa-sla-a_08* *aa-sla-a_09*)
                                 (#\b *aa-sla-b_00* *aa-sla-b_01* *aa-sla-b_02* *aa-sla-b_03* *aa-sla-b_04* *aa-sla-b_05* *aa-sla-b_06* *aa-sla-b_07* *aa-sla-b_08* *aa-sla-b_09*)
                                 (#\c *aa-sla-c_00* *aa-sla-c_01* *aa-sla-c_02* *aa-sla-c_03* *aa-sla-c_04* *aa-sla-c_05* *aa-sla-c_06* *aa-sla-c_07* *aa-sla-c_08* *aa-sla-c_09*)
                                 (#\d *aa-sla-d_00* *aa-sla-d_01* *aa-sla-d_02* *aa-sla-d_03* *aa-sla-d_04* *aa-sla-d_05* *aa-sla-d_06* *aa-sla-d_07* *aa-sla-d_08* *aa-sla-d_09*)
                                 (#\e *aa-sla-e_00* *aa-sla-e_01* *aa-sla-e_02* *aa-sla-e_03* *aa-sla-e_04* *aa-sla-e_05* *aa-sla-e_06* *aa-sla-e_07* *aa-sla-e_08* *aa-sla-e_09*)
                                 (#\f *aa-sla-f_00* *aa-sla-f_01* *aa-sla-f_02* *aa-sla-f_03* *aa-sla-f_04* *aa-sla-f_05* *aa-sla-f_06* *aa-sla-f_07* *aa-sla-f_08* *aa-sla-f_09*)
                                 (#\g *aa-sla-g_00* *aa-sla-g_01* *aa-sla-g_02* *aa-sla-g_03* *aa-sla-g_04* *aa-sla-g_05* *aa-sla-g_06* *aa-sla-g_07* *aa-sla-g_08* *aa-sla-g_09*)
                                 (#\h *aa-sla-h_00* *aa-sla-h_01* *aa-sla-h_02* *aa-sla-h_03* *aa-sla-h_04* *aa-sla-h_05* *aa-sla-h_06* *aa-sla-h_07* *aa-sla-h_08* *aa-sla-h_09*)
                                 (#\i *aa-sla-i_00* *aa-sla-i_01* *aa-sla-i_02* *aa-sla-i_03* *aa-sla-i_04* *aa-sla-i_05* *aa-sla-i_06* *aa-sla-i_07* *aa-sla-i_08* *aa-sla-i_09*)
                                 (#\j *aa-sla-j_00* *aa-sla-j_01* *aa-sla-j_02* *aa-sla-j_03* *aa-sla-j_04* *aa-sla-j_05* *aa-sla-j_06* *aa-sla-j_07* *aa-sla-j_08* *aa-sla-j_09*)
                                 (#\k *aa-sla-k_00* *aa-sla-k_01* *aa-sla-k_02* *aa-sla-k_03* *aa-sla-k_04* *aa-sla-k_05* *aa-sla-k_06* *aa-sla-k_07* *aa-sla-k_08* *aa-sla-k_09*)
                                 (#\l *aa-sla-l_00* *aa-sla-l_01* *aa-sla-l_02* *aa-sla-l_03* *aa-sla-l_04* *aa-sla-l_05* *aa-sla-l_06* *aa-sla-l_07* *aa-sla-l_08* *aa-sla-l_09*)
                                 (#\m *aa-sla-m_00* *aa-sla-m_01* *aa-sla-m_02* *aa-sla-m_03* *aa-sla-m_04* *aa-sla-m_05* *aa-sla-m_06* *aa-sla-m_07* *aa-sla-m_08* *aa-sla-m_09*)
                                 (#\n *aa-sla-n_00* *aa-sla-n_01* *aa-sla-n_02* *aa-sla-n_03* *aa-sla-n_04* *aa-sla-n_05* *aa-sla-n_06* *aa-sla-n_07* *aa-sla-n_08* *aa-sla-n_09*)
                                 (#\o *aa-sla-o_00* *aa-sla-o_01* *aa-sla-o_02* *aa-sla-o_03* *aa-sla-o_04* *aa-sla-o_05* *aa-sla-o_06* *aa-sla-o_07* *aa-sla-o_08* *aa-sla-o_09*)
                                 (#\p *aa-sla-p_00* *aa-sla-p_01* *aa-sla-p_02* *aa-sla-p_03* *aa-sla-p_04* *aa-sla-p_05* *aa-sla-p_06* *aa-sla-p_07* *aa-sla-p_08* *aa-sla-p_09*)
                                 (#\q *aa-sla-q_00* *aa-sla-q_01* *aa-sla-q_02* *aa-sla-q_03* *aa-sla-q_04* *aa-sla-q_05* *aa-sla-q_06* *aa-sla-q_07* *aa-sla-q_08* *aa-sla-q_09*)
                                 (#\r *aa-sla-r_00* *aa-sla-r_01* *aa-sla-r_02* *aa-sla-r_03* *aa-sla-r_04* *aa-sla-r_05* *aa-sla-r_06* *aa-sla-r_07* *aa-sla-r_08* *aa-sla-r_09*)
                                 (#\s *aa-sla-s_00* *aa-sla-s_01* *aa-sla-s_02* *aa-sla-s_03* *aa-sla-s_04* *aa-sla-s_05* *aa-sla-s_06* *aa-sla-s_07* *aa-sla-s_08* *aa-sla-s_09*)
                                 (#\t *aa-sla-t_00* *aa-sla-t_01* *aa-sla-t_02* *aa-sla-t_03* *aa-sla-t_04* *aa-sla-t_05* *aa-sla-t_06* *aa-sla-t_07* *aa-sla-t_08* *aa-sla-t_09*)
                                 (#\u *aa-sla-u_00* *aa-sla-u_01* *aa-sla-u_02* *aa-sla-u_03* *aa-sla-u_04* *aa-sla-u_05* *aa-sla-u_06* *aa-sla-u_07* *aa-sla-u_08* *aa-sla-u_09*)
                                 (#\v *aa-sla-v_00* *aa-sla-v_01* *aa-sla-v_02* *aa-sla-v_03* *aa-sla-v_04* *aa-sla-v_05* *aa-sla-v_06* *aa-sla-v_07* *aa-sla-v_08* *aa-sla-v_09*)
                                 (#\w *aa-sla-w_00* *aa-sla-w_01* *aa-sla-w_02* *aa-sla-w_03* *aa-sla-w_04* *aa-sla-w_05* *aa-sla-w_06* *aa-sla-w_07* *aa-sla-w_08* *aa-sla-w_09*)
                                 (#\x *aa-sla-x_00* *aa-sla-x_01* *aa-sla-x_02* *aa-sla-x_03* *aa-sla-x_04* *aa-sla-x_05* *aa-sla-x_06* *aa-sla-x_07* *aa-sla-x_08* *aa-sla-x_09*)
                                 (#\y *aa-sla-y_00* *aa-sla-y_01* *aa-sla-y_02* *aa-sla-y_03* *aa-sla-y_04* *aa-sla-y_05* *aa-sla-y_06* *aa-sla-y_07* *aa-sla-y_08* *aa-sla-y_09*)
                                 (#\z *aa-sla-z_00* *aa-sla-z_01* *aa-sla-z_02* *aa-sla-z_03* *aa-sla-z_04* *aa-sla-z_05* *aa-sla-z_06* *aa-sla-z_07* *aa-sla-z_08* *aa-sla-z_09*)
                                 (#\A *aa-sla-La_00* *aa-sla-La_01* *aa-sla-La_02* *aa-sla-La_03* *aa-sla-La_04* *aa-sla-La_05* *aa-sla-La_06* *aa-sla-La_07* *aa-sla-La_08* *aa-sla-La_09*)
                                 (#\B *aa-sla-Lb_00* *aa-sla-Lb_01* *aa-sla-Lb_02* *aa-sla-Lb_03* *aa-sla-Lb_04* *aa-sla-Lb_05* *aa-sla-Lb_06* *aa-sla-Lb_07* *aa-sla-Lb_08* *aa-sla-Lb_09*)
                                 (#\C *aa-sla-Lc_00* *aa-sla-Lc_01* *aa-sla-Lc_02* *aa-sla-Lc_03* *aa-sla-Lc_04* *aa-sla-Lc_05* *aa-sla-Lc_06* *aa-sla-Lc_07* *aa-sla-Lc_08* *aa-sla-Lc_09*)
                                 (#\D *aa-sla-Ld_00* *aa-sla-Ld_01* *aa-sla-Ld_02* *aa-sla-Ld_03* *aa-sla-Ld_04* *aa-sla-Ld_05* *aa-sla-Ld_06* *aa-sla-Ld_07* *aa-sla-Ld_08* *aa-sla-Ld_09*)
                                 (#\E *aa-sla-Le_00* *aa-sla-Le_01* *aa-sla-Le_02* *aa-sla-Le_03* *aa-sla-Le_04* *aa-sla-Le_05* *aa-sla-Le_06* *aa-sla-Le_07* *aa-sla-Le_08* *aa-sla-Le_09*)
                                 (#\F *aa-sla-Lf_00* *aa-sla-Lf_01* *aa-sla-Lf_02* *aa-sla-Lf_03* *aa-sla-Lf_04* *aa-sla-Lf_05* *aa-sla-Lf_06* *aa-sla-Lf_07* *aa-sla-Lf_08* *aa-sla-Lf_09*)
                                 (#\G *aa-sla-Lg_00* *aa-sla-Lg_01* *aa-sla-Lg_02* *aa-sla-Lg_03* *aa-sla-Lg_04* *aa-sla-Lg_05* *aa-sla-Lg_06* *aa-sla-Lg_07* *aa-sla-Lg_08* *aa-sla-Lg_09*)
                                 (#\H *aa-sla-Lh_00* *aa-sla-Lh_01* *aa-sla-Lh_02* *aa-sla-Lh_03* *aa-sla-Lh_04* *aa-sla-Lh_05* *aa-sla-Lh_06* *aa-sla-Lh_07* *aa-sla-Lh_08* *aa-sla-Lh_09*)
                                 (#\I *aa-sla-Li_00* *aa-sla-Li_01* *aa-sla-Li_02* *aa-sla-Li_03* *aa-sla-Li_04* *aa-sla-Li_05* *aa-sla-Li_06* *aa-sla-Li_07* *aa-sla-Li_08* *aa-sla-Li_09*)
                                 (#\J *aa-sla-Lj_00* *aa-sla-Lj_01* *aa-sla-Lj_02* *aa-sla-Lj_03* *aa-sla-Lj_04* *aa-sla-Lj_05* *aa-sla-Lj_06* *aa-sla-Lj_07* *aa-sla-Lj_08* *aa-sla-Lj_09*)
                                 (#\K *aa-sla-Lk_00* *aa-sla-Lk_01* *aa-sla-Lk_02* *aa-sla-Lk_03* *aa-sla-Lk_04* *aa-sla-Lk_05* *aa-sla-Lk_06* *aa-sla-Lk_07* *aa-sla-Lk_08* *aa-sla-Lk_09*)
                                 (#\L *aa-sla-Ll_00* *aa-sla-Ll_01* *aa-sla-Ll_02* *aa-sla-Ll_03* *aa-sla-Ll_04* *aa-sla-Ll_05* *aa-sla-Ll_06* *aa-sla-Ll_07* *aa-sla-Ll_08* *aa-sla-Ll_09*)
                                 (#\M *aa-sla-Lm_00* *aa-sla-Lm_01* *aa-sla-Lm_02* *aa-sla-Lm_03* *aa-sla-Lm_04* *aa-sla-Lm_05* *aa-sla-Lm_06* *aa-sla-Lm_07* *aa-sla-Lm_08* *aa-sla-Lm_09*)
                                 (#\N *aa-sla-Ln_00* *aa-sla-Ln_01* *aa-sla-Ln_02* *aa-sla-Ln_03* *aa-sla-Ln_04* *aa-sla-Ln_05* *aa-sla-Ln_06* *aa-sla-Ln_07* *aa-sla-Ln_08* *aa-sla-Ln_09*)
                                 (#\O *aa-sla-Lo_00* *aa-sla-Lo_01* *aa-sla-Lo_02* *aa-sla-Lo_03* *aa-sla-Lo_04* *aa-sla-Lo_05* *aa-sla-Lo_06* *aa-sla-Lo_07* *aa-sla-Lo_08* *aa-sla-Lo_09*)
                                 (#\P *aa-sla-Lp_00* *aa-sla-Lp_01* *aa-sla-Lp_02* *aa-sla-Lp_03* *aa-sla-Lp_04* *aa-sla-Lp_05* *aa-sla-Lp_06* *aa-sla-Lp_07* *aa-sla-Lp_08* *aa-sla-Lp_09*)
                                 (#\Q *aa-sla-Lq_00* *aa-sla-Lq_01* *aa-sla-Lq_02* *aa-sla-Lq_03* *aa-sla-Lq_04* *aa-sla-Lq_05* *aa-sla-Lq_06* *aa-sla-Lq_07* *aa-sla-Lq_08* *aa-sla-Lq_09*)
                                 (#\R *aa-sla-Lr_00* *aa-sla-Lr_01* *aa-sla-Lr_02* *aa-sla-Lr_03* *aa-sla-Lr_04* *aa-sla-Lr_05* *aa-sla-Lr_06* *aa-sla-Lr_07* *aa-sla-Lr_08* *aa-sla-Lr_09*)
                                 (#\S *aa-sla-Ls_00* *aa-sla-Ls_01* *aa-sla-Ls_02* *aa-sla-Ls_03* *aa-sla-Ls_04* *aa-sla-Ls_05* *aa-sla-Ls_06* *aa-sla-Ls_07* *aa-sla-Ls_08* *aa-sla-Ls_09*)
                                 (#\T *aa-sla-Lt_00* *aa-sla-Lt_01* *aa-sla-Lt_02* *aa-sla-Lt_03* *aa-sla-Lt_04* *aa-sla-Lt_05* *aa-sla-Lt_06* *aa-sla-Lt_07* *aa-sla-Lt_08* *aa-sla-Lt_09*)
                                 (#\U *aa-sla-Lu_00* *aa-sla-Lu_01* *aa-sla-Lu_02* *aa-sla-Lu_03* *aa-sla-Lu_04* *aa-sla-Lu_05* *aa-sla-Lu_06* *aa-sla-Lu_07* *aa-sla-Lu_08* *aa-sla-Lu_09*)
                                 (#\V *aa-sla-Lv_00* *aa-sla-Lv_01* *aa-sla-Lv_02* *aa-sla-Lv_03* *aa-sla-Lv_04* *aa-sla-Lv_05* *aa-sla-Lv_06* *aa-sla-Lv_07* *aa-sla-Lv_08* *aa-sla-Lv_09*)
                                 (#\W *aa-sla-Lw_00* *aa-sla-Lw_01* *aa-sla-Lw_02* *aa-sla-Lw_03* *aa-sla-Lw_04* *aa-sla-Lw_05* *aa-sla-Lw_06* *aa-sla-Lw_07* *aa-sla-Lw_08* *aa-sla-Lw_09*)
                                 (#\X *aa-sla-Lx_00* *aa-sla-Lx_01* *aa-sla-Lx_02* *aa-sla-Lx_03* *aa-sla-Lx_04* *aa-sla-Lx_05* *aa-sla-Lx_06* *aa-sla-Lx_07* *aa-sla-Lx_08* *aa-sla-Lx_09*)
                                 (#\Y *aa-sla-Ly_00* *aa-sla-Ly_01* *aa-sla-Ly_02* *aa-sla-Ly_03* *aa-sla-Ly_04* *aa-sla-Ly_05* *aa-sla-Ly_06* *aa-sla-Ly_07* *aa-sla-Ly_08* *aa-sla-Ly_09*)
                                 (#\Z *aa-sla-Lz_00* *aa-sla-Lz_01* *aa-sla-Lz_02* *aa-sla-Lz_03* *aa-sla-Lz_04* *aa-sla-Lz_05* *aa-sla-Lz_06* *aa-sla-Lz_07* *aa-sla-Lz_08* *aa-sla-Lz_09*)
                                 (#\. *aa-sla-dot_00* *aa-sla-dot_01* *aa-sla-dot_02* *aa-sla-dot_03* *aa-sla-dot_04* *aa-sla-dot_05* *aa-sla-dot_06* *aa-sla-dot_07* *aa-sla-dot_08* *aa-sla-dot_09*)
                                 (#\! *aa-sla-exc_00* *aa-sla-exc_01* *aa-sla-exc_02* *aa-sla-exc_03* *aa-sla-exc_04* *aa-sla-exc_05* *aa-sla-exc_06* *aa-sla-exc_07* *aa-sla-exc_08* *aa-sla-exc_09*)
                                 (#\? *aa-sla-Question_00* *aa-sla-Question_01* *aa-sla-Question_02* *aa-sla-Question_03* *aa-sla-Question_04* *aa-sla-Question_05* *aa-sla-Question_06* *aa-sla-Question_07* *aa-sla-Question_08* *aa-sla-Question_09*)
                                 (#\- *aa-sla-hyphen_00* *aa-sla-hyphen_01* *aa-sla-hyphen_02* *aa-sla-hyphen_03* *aa-sla-hyphen_04* *aa-sla-hyphen_05* *aa-sla-hyphen_06* *aa-sla-hyphen_07* *aa-sla-hyphen_08* *aa-sla-hyphen_09*)
                                 (#\Space *aa-sla-Space_00* *aa-sla-Space_01* *aa-sla-Space_02* *aa-sla-Space_03* *aa-sla-Space_04* *aa-sla-Space_05* *aa-sla-Space_06* *aa-sla-Space_07* *aa-sla-Space_08* *aa-sla-Space_09*)))
;}}}
; fresh-princ{{{
(defun fresh-princ(str)
  (princ str)
  (fresh-line))
;}}}
; ca...dr{{{
(defun caddddr (lst)
  (car (cdr (cdr (cdr (cdr lst))))))

(defun cadddddr (lst)
  (car (cdr (cdr (cdr (cdr (cdr lst)))))))

(defun caddddddr (lst)
  (car (cdr (cdr (cdr (cdr (cdr (cdr lst))))))))

(defun cadddddddr (lst)
  (car (cdr (cdr (cdr (cdr (cdr (cdr (cdr lst)))))))))

(defun caddddddddr (lst)
  (car (cdr (cdr (cdr (cdr (cdr (cdr (cdr (cdr lst))))))))))

(defun cadddddddddr (lst)
  (car (cdr (cdr (cdr (cdr (cdr (cdr (cdr (cdr (cdr lst)))))))))))

(defun caddddddddddr (lst)
  (car (car (car (cdr (cdr (cdr (cdr (cdr (cdr (cdr (cdr lst))))))))))))
;}}}

; for aa-print{{{
; charlist-to-aa-line{{{

(defun charlist-to-aaline (charlist line-num nodes)
  (let* ((aa-candidates 
           (cdr (assoc (car charlist) nodes)))
         (aa-string (symbol-value (case line-num 
                                    (0 (car aa-candidates))
                                    (1 (cadr aa-candidates))
                                    (2 (caddr aa-candidates))
                                    (3 (cadddr aa-candidates))
                                    (4 (caddddr aa-candidates))
                                    (5 (cadddddr aa-candidates))
                                    (6 (caddddddr aa-candidates))
                                    (7 (cadddddddr aa-candidates))))))
    (if charlist
      (concatenate 'string aa-string
                   (charlist-to-aaline (cdr charlist) line-num nodes))
      " ")))
;}}}
; charlist-to-aa-print{{{

(defun charlist-to-aa-print (charlist nodes)
  (fresh-line)
  (loop for i from 0 to 7
        collect (fresh-princ (charlist-to-aaline charlist i  nodes))))
; (charlist-to-aa-print '(#\T #\e #\s #\t) *aa-nodes*)

;}}}
; string-to-charlist{{{

(defun string-to-charlist (str)
  (if (equal "" str)
    (list #\Space)
    (concatenate 'list
                 (list (char str '0))
                 (string-to-charlist (substring str '1)))))
; (print (to-charlist "test"))
; "test" -> (#\t #\e #\s #\t #\Space) 
;}}}
;}}}
; for aa-sla-print{{{
; charlist-to-aa-sla-line{{{

(defun charlist-to-aa-sla-line (charlist line-num nodes)
  (let* ((aa-candidates 
           (cdr (assoc (car charlist) nodes)))
         (aa-string (symbol-value (case line-num 
                                    (0 (car aa-candidates))
                                    (1 (cadr aa-candidates))
                                    (2 (caddr aa-candidates))
                                    (3 (cadddr aa-candidates))
                                    (4 (caddddr aa-candidates))
                                    (5 (cadddddr aa-candidates))
                                    (6 (caddddddr aa-candidates))
                                    (7 (cadddddddr aa-candidates))
                                    (8 (caddddddddr aa-candidates))
                                    (9 (cadddddddddr aa-candidates))))))
    (if charlist
      (concatenate 'string aa-string
                   (charlist-to-aa-sla-line (cdr charlist) line-num nodes))
      " ")))
;}}}
; charlist-to-aa-sla-print{{{

(defun charlist-to-aa-sla-print (charlist nodes)
  (fresh-line)
  (loop for i from 0 to 9
        collect (fresh-princ (charlist-to-aa-sla-line charlist i  nodes))))
; (charlist-to-aa-print '(#\T #\e #\s #\t) *aa-nodes*)

;}}}
;}}}

(defun aa-print(str)
  (charlist-to-aa-print (string-to-charlist str) *aa-nodes*))

(defun aa-sla-print(str)
  (charlist-to-aa-sla-print (string-to-charlist str) *aa-slash-nodes*))

; demo
(aa-print "youji daisuki")
; (aa-print "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890")
; (aa-sla-print "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890")
